import React from 'react';
import { Download, Copy } from 'lucide-react';
import { TwoFactorSectionProps } from '../interfaces/two-factor-section-props.interface';
import styles from './two-factor-section.module.css';

export const TwoFactorSectionTemplate: React.FC<TwoFactorSectionProps> = ({
  is2faEnabled,
  twoFactorStep,
  setTwoFactorStep,
  qrCodeUrl,
  totpSecret,
  verificationCode,
  setVerificationCode,
  handleSetup2FA,
  handleEnable2FA,
  handleDisable2FA,
  recoveryCodes,
  setRecoveryCodes,
  showToast,
}) => {
  return (
    <section className={styles.section}>
      <h2 className={styles.sectionHeader}>Two-factor Authentication</h2>
      <div className={styles.settingList}>
        <div className={styles.settingRow}>
          <div className={styles.settingInfo}>
            <span className={styles.settingLabel}>Authenticator App</span>
            <span
              className={`${styles.settingDesc} ${is2faEnabled ? styles.activeStatus : styles.inactiveStatus}`}
            >
              {is2faEnabled ? 'Active (Secured with TOTP)' : 'Inactive (Recommended)'}
            </span>
            <span className={`${styles.settingDesc} ${styles.settingDescSmall}`}>
              Two-factor authentication (2FA) adds a vital layer of security. When signing in, you will be prompted for a 6-digit one-time passcode generated by your authenticator app (such as Google Authenticator, Microsoft Authenticator, Authy, or 1Password) in addition to your master password.
            </span>
          </div>
          <div className={styles.settingAction}>
            {is2faEnabled ? (
              twoFactorStep === 'disable' ? null : (
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnSecondary}`}
                  onClick={() => setTwoFactorStep('disable')}
                >
                  Disable 2FA
                </button>
              )
            ) : (
              (twoFactorStep === 'setup' || recoveryCodes.length > 0) ? null : (
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnSecondary}`}
                  onClick={handleSetup2FA}
                >
                  Enable 2FA
                </button>
              )
            )}
          </div>
        </div>

        <div className={`${styles.expandableArea} ${(twoFactorStep === 'setup' || recoveryCodes.length > 0) ? styles.active : ''}`}>
          {recoveryCodes.length > 0 ? (
            <div className={styles.recoveryCodeContainer}>
              <div className={styles.successAlert}>
                <span className={styles.successAlertIcon}>✓</span>
                <div>
                  <strong className={styles.successAlertTitle}>Two-Factor Authentication is Enabled!</strong>
                  <span className={styles.successAlertDesc}>Save these recovery codes. If you lose your authenticator device, these codes are the only way to recover access to your account.</span>
                </div>
              </div>

              <div className={styles.recoveryGrid}>
                {recoveryCodes.map((code, idx) => (
                  <div key={idx} className={styles.recoveryCodeBox}>
                    {code}
                  </div>
                ))}
              </div>

              <div className={styles.tipText}>
                <span className={styles.tipEmoji}>💡</span>
                <span>Tip: Store these codes in Bitwarden as a <strong>Hidden Custom Field</strong> named <code>code</code> for secure recovery autofill.</span>
              </div>

              <div className={styles.btnRow}>
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnSecondary}`}
                  onClick={() => {
                    navigator.clipboard.writeText(recoveryCodes.join('\n'));
                    if (showToast) showToast('Recovery codes copied to clipboard!', 'success');
                  }}
                  title="Copy recovery codes"
                >
                  <Copy size={14} />
                </button>
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnSecondary}`}
                  onClick={() => {
                    const element = document.createElement('a');
                    const file = new Blob([recoveryCodes.join('\n')], { type: 'text/plain' });
                    element.href = URL.createObjectURL(file);
                    element.download = 'giftistry-recovery-codes.txt';
                    document.body.appendChild(element);
                    element.click();
                    document.body.removeChild(element);
                  }}
                  title="Download recovery codes"
                >
                  <Download size={14} />
                </button>
                <button
                  type="button"
                  className={`${styles.btn} ${styles.btnSecondary} ${styles.btnRightAligned}`}
                  onClick={() => {
                    setRecoveryCodes([]);
                    setTwoFactorStep('none');
                  }}
                >
                  Done & Close
                </button>
              </div>
            </div>
          ) : (
            <div className={styles.setupGrid}>
              {qrCodeUrl && (
                <div className={styles.qrCodeWrapper}>
                  <img src={qrCodeUrl} alt="2FA QR Code" className={styles.qrImage} />
                </div>
              )}
              <div className={styles.setupRightColumn}>
                <span className={`${styles.settingLabel} ${styles.labelBold}`}>Scan QR Code</span>
                <span className={`${styles.settingDesc} ${styles.lineHeightNormal}`}>
                  Use your preferred authenticator app (like Google Authenticator, Microsoft Authenticator, Authy, or 1Password) to scan the QR code.
                </span>
                {totpSecret && (
                  <div className={styles.manualSecretWrapper}>
                    <span className={`${styles.settingDesc} ${styles.manualSecretTitle}`}>Or enter code manually:</span>
                    <code className={styles.totpSecretCode}>{totpSecret}</code>
                  </div>
                )}

                <form onSubmit={handleEnable2FA} className={styles.inlineForm}>
                  <div className={`${styles.inputWrapper} ${styles.verificationInputWrapper}`}>
                    <input
                      type="text"
                      pattern="[0-9]*"
                      maxLength={6}
                      id="two-factor-code"
                      name="code"
                      autoComplete="one-time-code"
                      placeholder="000000"
                      className={styles.inputField}
                      value={verificationCode}
                      onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
                      required
                    />
                  </div>
                  <button type="submit" className={`${styles.btn} ${styles.btnPrimary}`}>Verify & Enable</button>
                  <button type="button" className={`${styles.btn} ${styles.btnSecondary}`} onClick={() => setTwoFactorStep('none')}>
                    Cancel
                  </button>
                </form>
              </div>
            </div>
          )}
        </div>

        <div className={`${styles.expandableArea} ${twoFactorStep === 'disable' ? styles.active : ''}`}>
          <div className={`${styles.settingInfo} ${styles.flexCol} ${styles.gap2} ${styles.wFull}`}>
            <span className={`${styles.settingLabel} ${styles.dangerText}`}>Disable Two-Factor Authentication</span>
            <span className={`${styles.settingDesc} ${styles.descMaxWidth}`}>
              To turn off Two-Factor Authentication, please enter a 6-digit verification code from your authenticator app (or one of your 10-character recovery codes) to verify your identity.
            </span>

            <form onSubmit={handleDisable2FA} className={styles.inlineForm}>
              <div className={`${styles.inputWrapper} ${styles.verificationInputWrapper}`}>
                <input
                  type="text"
                  id="disable-two-factor-code"
                  name="code"
                  autoComplete="one-time-code"
                  placeholder="000000 / Recovery Code"
                  className={`${styles.inputField} ${styles.fullWidthInput}`}
                  value={verificationCode}
                  onChange={(e) => setVerificationCode(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className={`${styles.btn} ${styles.btnDangerSolid}`}>
                Confirm Disable
              </button>
              <button
                type="button"
                className={`${styles.btn} ${styles.btnSecondary}`}
                onClick={() => {
                  setVerificationCode('');
                  setTwoFactorStep('none');
                }}
              >
                Cancel
              </button>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
};
