import type { BackendSettings } from '../interfaces/backend-settings.interface';
import type { SettingsPayloadInput } from '../interfaces/settings-payload-input.interface';

export function buildSettingsPayload(
  input: SettingsPayloadInput,
  overrides?: { AllowSetup?: boolean },
): BackendSettings {
  return {
    DbType: input.dbType,
    DbUrl: input.dbType === 'remote' ? input.dbUrl : '',
    PublicAppUrl: input.publicAppUrl.trim(),
    OAuthEnabled: input.oauthEnabled,
    OAuthIssuerUrl: input.oauthIssuerUrl.trim(),
    OAuthClientId: input.oauthClientId.trim(),
    OAuthClientSecret: input.oauthClientSecret,
    OAuthAutoRegister: input.oauthAutoRegister,
    SmtpType: input.smtpType,
    SmtpHost: input.smtpType === 'remote' ? input.smtpHost : '',
    SmtpPort: input.smtpType === 'remote' ? Number(input.smtpPort) : 1025,
    SmtpUser: input.smtpType === 'remote' ? input.smtpUser : '',
    SmtpPass: input.smtpType === 'remote' ? input.smtpPass : '',
    SmtpSecure: input.smtpType === 'remote' ? input.smtpSecure : false,
    SmtpFrom: input.smtpType === 'remote' ? input.smtpFrom : 'noreply@giftistry.local',
    NtfyEnabled: input.ntfyEnabled,
    NtfyBaseUrl: input.ntfyBaseUrl.trim(),
    NtfyAuthToken: input.ntfyAuthToken,
    NtfyTopicPrefix: input.ntfyTopicPrefix.trim() || 'giftistry',
    WebPushEnabled: input.webPushEnabled,
    WebPushVapidPublicKey: input.webPushVapidPublicKey.trim(),
    WebPushVapidPrivateKey: input.webPushVapidPrivateKey,
    WebPushSubject: input.webPushSubject.trim() || 'mailto:admin@localhost',
    FcmEnabled: input.fcmEnabled,
    FcmProjectId: input.fcmProjectId.trim(),
    FcmServiceAccountJson: input.fcmServiceAccountJson,
    AiEnabled: input.aiEnabled,
    AiWebSearchEnabled: input.aiWebSearchEnabled,
    AiRateLimitEnabled: input.aiRateLimitEnabled,
    AiImportChunkingEnabled: input.aiImportChunkingEnabled,
    AiImportChunkItemLimit: input.aiImportChunkItemLimit,
    AiCompletionTimeoutMs: input.aiCompletionTimeoutMs,
    AiConnectTimeoutMs: input.aiConnectTimeoutMs,
    ScrapeFetchTimeoutMs: input.scrapeFetchTimeoutMs,
    ScrapePlaywrightTimeoutMs: input.scrapePlaywrightTimeoutMs,
    GrabInfoConcurrency: input.grabInfoConcurrency,
    GrabInfoConcurrencyUnlimited: input.grabInfoConcurrencyUnlimited,
    GrabInfoActiveStreamLimit: input.grabInfoActiveStreamLimit,
    AiFastProvider: input.aiFastProvider,
    AiFastEndpoint: input.aiFastEndpoint,
    AiFastApiKey: input.aiFastApiKey,
    AiFastModel: input.aiFastModel,
    AiIntelligentProvider: input.aiIntelligentProvider,
    AiIntelligentEndpoint: input.aiIntelligentEndpoint,
    AiIntelligentApiKey: input.aiIntelligentApiKey,
    AiIntelligentModel: input.aiIntelligentModel,
    AiPrompt: input.aiPrompt,
    AiDescriptionPrompt: input.aiDescriptionPrompt,
    AiPopulatePrompt: input.aiPopulatePrompt,
    AiCategoryPrompt: input.aiCategoryPrompt,
    AiImportPrompt: input.aiImportPrompt,
    AiEnabledPackIds: input.aiEnabledPackIds,
    AiCustomPacks: input.aiCustomPacks,
    AllowSetup: overrides?.AllowSetup ?? input.allowSetup,
  };
}
