import { TOUR_TARGETS } from './targets.constant';
import type { TourStepDef } from '../interfaces/step-def.interface';

export const TOUR_STEPS: TourStepDef[] = [
  // —— demo ——
  {
    id: 'demo-welcome',
    chapterId: 'demo',
    title: 'Welcome to Giftistry',
    body: 'A short tour of wishlists, gifts, and sharing. Nothing in the sample is saved to your account.',
    isDialog: true,
    isWelcome: true,
    center: true,
    nextLabel: 'Start tutorial',
    skipLabel: 'Close',
  },
  {
    id: 'demo-grid',
    chapterId: 'demo',
    title: 'Gifts on the list',
    body: 'This sample already has a couple of ideas. In a moment, a collaborator will add another.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.demoItems, placement: 'bottom', beforeShow: 'navigateDemo' },
    mobile: { target: TOUR_TARGETS.demoItems, placement: 'top', beforeShow: 'navigateDemo' },
    demoBeat: 'seed',
  },
  {
    id: 'demo-add',
    chapterId: 'demo',
    title: 'Jordan added a gift',
    body: 'Collaborators can add items while you browse. Watch for new cards as people contribute.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.demoNewItem, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.demoNewItem, placement: 'top' },
    demoBeat: 'addItem',
  },
  {
    id: 'demo-discussion',
    chapterId: 'demo',
    title: 'Open Discussion',
    body: 'Click Discussion to see comments and typing as people chat about gifts.',
    advanceOn: 'target',
    hintText: 'Click Discussion to continue',
    desktop: { target: TOUR_TARGETS.discussion, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.commentsFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'demo-typing',
    chapterId: 'demo',
    title: 'Someone is typing…',
    body: 'Sam is typing in Discussion. Live updates help you coordinate without leaving the list.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.demoTyping, placement: 'top', beforeShow: 'openComments' },
    mobile: { target: TOUR_TARGETS.demoTyping, placement: 'top', beforeShow: 'openComments' },
    demoBeat: 'typing',
  },
  {
    id: 'demo-comment',
    chapterId: 'demo',
    title: 'A new comment',
    body: 'Sam offered to grab an item. Comments keep the conversation with the list.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.demoNewComment, placement: 'left', beforeShow: 'openComments' },
    mobile: { target: TOUR_TARGETS.demoNewComment, placement: 'top', beforeShow: 'openComments' },
    demoBeat: 'comment',
  },
  {
    id: 'demo-done',
    chapterId: 'demo',
    title: 'Ready to make yours?',
    body: 'That was a sample. Next you will create a real wishlist that belongs to you.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Create my list',
    skipLabel: 'I’m done for now',
  },

  // —— beginner ——
  {
    id: 'beginner-welcome',
    chapterId: 'beginner',
    title: 'Create your first list',
    body: 'Now create a real wishlist. We’ll walk you through adding an item and finding Share and Friends.',
    isDialog: true,
    center: true,
    nextLabel: 'Let’s go',
    skipLabel: 'Skip tutorial',
    desktop: { beforeShow: 'navigateDashboard' },
    mobile: { beforeShow: 'navigateDashboard' },
  },
  {
    id: 'beginner-create',
    chapterId: 'beginner',
    title: 'New Wishlist',
    body: 'Click New Wishlist to open the create form.',
    advanceOn: 'target',
    hintText: 'Click New Wishlist to continue',
    desktop: { target: TOUR_TARGETS.createWishlist, placement: 'bottom', beforeShow: 'navigateDashboard' },
    mobile: {
      target: TOUR_TARGETS.createWishlistFabAction,
      placement: 'top',
      beforeShow: ['navigateDashboard', 'openFab'],
    },
  },
  {
    id: 'beginner-title',
    chapterId: 'beginner',
    title: 'Name your list',
    body: 'Give it a title — for example “Birthday 2026” — then continue.',
    advanceOn: 'next',
    nextLabel: 'Continue',
    hintText: 'Type a title, then click Continue',
    desktop: { target: TOUR_TARGETS.createTitle, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.createTitle, placement: 'top' },
  },
  {
    id: 'beginner-submit',
    chapterId: 'beginner',
    title: 'Save the list',
    body: 'Create the wishlist to add it to your dashboard.',
    advanceOn: 'event',
    advanceEvent: 'tour:wishlist-created',
    desktop: { target: TOUR_TARGETS.createSubmit, placement: 'top' },
    mobile: { target: TOUR_TARGETS.createSubmit, placement: 'top' },
  },
  {
    id: 'beginner-open',
    chapterId: 'beginner',
    title: 'Open your list',
    body: 'Click the new card to open it.',
    advanceOn: 'route',
    routeIncludes: '/wishlists/',
    desktop: { target: TOUR_TARGETS.tourListCard, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.tourListCard, placement: 'top' },
  },
  {
    id: 'beginner-add',
    chapterId: 'beginner',
    title: 'Add an item',
    body: 'Click Add Manually to create your first gift idea.',
    advanceOn: 'event',
    advanceEvent: 'tour:add-drawer-opened',
    hintText: 'Click Add Manually to continue',
    desktop: { target: TOUR_TARGETS.addManually, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.addManually, placement: 'top' },
  },
  {
    id: 'beginner-save-item',
    chapterId: 'beginner',
    title: 'Save the item',
    body: 'Enter a name and save. This item is stored on your real list.',
    advanceOn: 'event',
    advanceEvent: 'tour:item-created',
    hintText: 'Enter a name and save to continue',
    desktop: { target: TOUR_TARGETS.addItemName, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.addItemName, placement: 'top' },
  },
  {
    id: 'beginner-share',
    chapterId: 'beginner',
    title: 'Share',
    body: 'Open Share to invite friends later. You do not need to share yet.',
    advanceOn: 'target',
    hintText: 'Open Share to continue',
    desktop: { target: TOUR_TARGETS.shareRegistry, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.shareFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'beginner-share-next',
    chapterId: 'beginner',
    title: 'Sharing options',
    body: 'You can invite friends, create a link, or manage access. Continue when you are ready.',
    advanceOn: 'next',
    center: true,
  },
  {
    id: 'beginner-friends',
    chapterId: 'beginner',
    title: 'Friends',
    body: 'Friends live under your profile. You can connect with people and see their lists.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.profileMenu, placement: 'bottom', beforeShow: 'closeShare' },
    mobile: { target: TOUR_TARGETS.hamburger, placement: 'bottom', beforeShow: 'closeShare' },
  },
  {
    id: 'beginner-done',
    chapterId: 'beginner',
    title: 'You are set',
    body: 'You created a list and an item. Continue for optional advanced tips, or finish and explore on your own.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
    desktop: { beforeShow: 'closeShare' },
    mobile: { beforeShow: 'closeShare' },
  },

  // —— importAi ——
  {
    id: 'import-welcome',
    chapterId: 'importAi',
    title: 'Import & auto-add',
    body: 'Import an export file or let AI pull details from a product link when available.',
    isDialog: true,
    center: true,
    nextLabel: 'Show me',
  },
  {
    id: 'import-button',
    chapterId: 'importAi',
    title: 'Import',
    body: 'Open Import to bring in a list file.',
    advanceOn: 'target',
    hintText: 'Open Import to continue',
    desktop: { target: TOUR_TARGETS.importWishlist, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.importFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'import-dropzone',
    chapterId: 'importAi',
    title: 'Drop a file',
    body: 'Drop a wishlist export here, or browse. You can skip without importing.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.importDropzone, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.importDropzone, placement: 'top' },
  },
  {
    id: 'import-auto-add',
    chapterId: 'importAi',
    title: 'Auto Add from Link',
    body: 'On a list with AI enabled, paste a product URL to auto-fill item details.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.autoAdd, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.autoAdd, placement: 'top' },
  },
  {
    id: 'import-done',
    chapterId: 'importAi',
    title: 'Import chapter done',
    body: 'You can return to Import anytime from the dashboard or list toolbar.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
  },

  // —— listTools ——
  {
    id: 'tools-welcome',
    chapterId: 'listTools',
    title: 'List tools',
    body: 'Change how items look, adjust list settings, and open Discussion.',
    isDialog: true,
    center: true,
  },
  {
    id: 'tools-views',
    chapterId: 'listTools',
    title: 'View modes',
    body: 'Switch between Detailed, Compact, Grid, and more.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.viewMode, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.viewMode, placement: 'top' },
  },
  {
    id: 'tools-settings',
    chapterId: 'listTools',
    title: 'List settings',
    body: 'Toggle AI, group funding, and other list options here.',
    advanceOn: 'target',
    hintText: 'Open list settings to continue',
    desktop: { target: TOUR_TARGETS.listSettings, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.settingsFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'tools-comments',
    chapterId: 'listTools',
    title: 'Discussion',
    body: 'Open Discussion on your real list anytime — even if there are no comments yet.',
    advanceOn: 'target',
    hintText: 'Open Discussion to continue',
    desktop: { target: TOUR_TARGETS.discussion, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.commentsFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'tools-done',
    chapterId: 'listTools',
    title: 'List tools done',
    body: 'View modes, settings, and Discussion are always on the list page.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
  },

  // —— shareDeep ——
  {
    id: 'share-welcome',
    chapterId: 'shareDeep',
    title: 'Sharing in depth',
    body: 'Invite friends, create a link with a role, and manage who has access.',
    isDialog: true,
    center: true,
  },
  {
    id: 'share-open',
    chapterId: 'shareDeep',
    title: 'Open Share',
    body: 'Open the share panel again.',
    advanceOn: 'target',
    hintText: 'Open Share to continue',
    desktop: { target: TOUR_TARGETS.shareRegistry, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.shareFab, placement: 'top', beforeShow: 'openFab' },
  },
  {
    id: 'share-friends-tab',
    chapterId: 'shareDeep',
    title: 'Friends tab',
    body: 'Share directly with people you are connected to.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.shareTabFriends, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.shareTabFriends, placement: 'top' },
  },
  {
    id: 'share-link-tab',
    chapterId: 'shareDeep',
    title: 'Link tab',
    body: 'Generate an invite link with a role and optional password.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.shareTabLink, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.shareTabLink, placement: 'top' },
  },
  {
    id: 'share-manage-tab',
    chapterId: 'shareDeep',
    title: 'Manage access',
    body: 'See who already has access and revoke when needed.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.shareTabManage, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.shareTabManage, placement: 'top' },
  },
  {
    id: 'share-done',
    chapterId: 'shareDeep',
    title: 'Sharing done',
    body: 'You can share lists whenever you are ready — no need to invite anyone during the tour.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
    desktop: { beforeShow: 'closeShare' },
    mobile: { beforeShow: 'closeShare' },
  },

  // —— friendsDeep ——
  {
    id: 'friends-welcome',
    chapterId: 'friendsDeep',
    title: 'Friends & Discover',
    body: 'Manage your network, requests, and find people to connect with.',
    isDialog: true,
    center: true,
  },
  {
    id: 'friends-current',
    chapterId: 'friendsDeep',
    title: 'My Friends',
    body: 'Your connections appear here.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.friendsTabCurrent, placement: 'bottom', beforeShow: 'navigateFriends' },
    mobile: { target: TOUR_TARGETS.friendsTabCurrent, placement: 'top', beforeShow: 'navigateFriends' },
  },
  {
    id: 'friends-requests',
    chapterId: 'friendsDeep',
    title: 'Requests',
    body: 'Incoming friend requests show up on this tab.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.friendsTabRequests, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.friendsTabRequests, placement: 'top' },
  },
  {
    id: 'friends-discover',
    chapterId: 'friendsDeep',
    title: 'Discover',
    body: 'Search for users to send a friend request.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.friendsTabDiscover, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.friendsTabDiscover, placement: 'top' },
  },
  {
    id: 'friends-done',
    chapterId: 'friendsDeep',
    title: 'Friends done',
    body: 'You can explore Discover anytime from the Friends page.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
  },

  // —— notifications ——
  {
    id: 'notify-welcome',
    chapterId: 'notifications',
    title: 'Notifications',
    body: 'Stay on top of claims, comments, and friend activity.',
    isDialog: true,
    center: true,
  },
  {
    id: 'notify-bell',
    chapterId: 'notifications',
    title: 'Notification bell',
    body: 'Open the bell in the top bar for recent activity.',
    advanceOn: 'target',
    hintText: 'Open the notification bell to continue',
    desktop: { target: TOUR_TARGETS.notificationBell, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.notificationBell, placement: 'bottom' },
  },
  {
    id: 'notify-settings',
    chapterId: 'notifications',
    title: 'Notification preferences',
    body: 'Choose which alerts you want in Settings → Notifications.',
    advanceOn: 'next',
    desktop: {
      target: TOUR_TARGETS.settingsNotifications,
      placement: 'right',
      beforeShow: 'navigateSettingsNotifications',
    },
    mobile: {
      target: TOUR_TARGETS.settingsNotifications,
      placement: 'bottom',
      beforeShow: 'navigateSettingsNotifications',
    },
  },
  {
    id: 'notify-done',
    chapterId: 'notifications',
    title: 'Notifications done',
    body: 'You can change preferences anytime.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Continue',
    skipLabel: 'I’m done for now',
  },

  // —— theming ——
  {
    id: 'theme-welcome',
    chapterId: 'theming',
    title: 'Theming',
    body: 'Pick a look that fits you — theme presets and light/dark appearance.',
    isDialog: true,
    center: true,
  },
  {
    id: 'theme-menu',
    chapterId: 'theming',
    title: 'Theme settings',
    body: 'Open theme settings from the navigation bar (or your profile sheet on mobile).',
    advanceOn: 'target',
    hintText: 'Open theme settings to continue',
    desktop: { target: TOUR_TARGETS.themeMenu, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.hamburger, placement: 'bottom' },
  },
  {
    id: 'theme-sheet',
    chapterId: 'theming',
    title: 'Appearance',
    body: 'Try a preset or switch light/dark. Full customizer lives under Settings → Theming.',
    advanceOn: 'next',
    desktop: { target: TOUR_TARGETS.themeMenu, placement: 'bottom' },
    mobile: { target: TOUR_TARGETS.profileTheming, placement: 'top' },
  },
  {
    id: 'theme-done',
    chapterId: 'theming',
    title: 'You are done',
    body: 'That covers the product tour. Restart any chapter later from Settings → Account.',
    isDialog: true,
    isChapterEnd: true,
    center: true,
    nextLabel: 'Finish',
    skipLabel: 'I’m done for now',
  },
];

export function stepsForChapter(chapterId: string): TourStepDef[] {
  return TOUR_STEPS.filter((step) => step.chapterId === chapterId);
}
