export const TOUR_DEMO_LIST_ID = 'tour-demo';

export const TOUR_TARGETS = {
  createWishlist: 'create-wishlist',
  createWishlistFab: 'create-wishlist-fab',
  createWishlistFabAction: 'create-wishlist-fab-action',
  createTitle: 'create-title',
  createSubmit: 'create-submit',
  tourListCard: 'tour-list-card',
  addManually: 'add-manually',
  addItemName: 'add-item-name',
  addItemSave: 'add-item-save',
  shareRegistry: 'share-registry',
  shareFab: 'share-fab',
  profileMenu: 'profile-menu',
  hamburger: 'hamburger',
  friendsAction: 'friends-action',
  demoItems: 'demo-items',
  demoNewItem: 'demo-new-item',
  demoTyping: 'demo-typing',
  demoComments: 'demo-comments',
  demoNewComment: 'demo-new-comment',
  discussion: 'discussion',
  commentsFab: 'comments-fab',
  importWishlist: 'import-wishlist',
  importFab: 'import-fab',
  importDropzone: 'import-dropzone',
  autoAdd: 'auto-add',
  viewMode: 'view-mode',
  listSettings: 'list-settings',
  settingsFab: 'settings-fab',
  shareTabFriends: 'share-tab-friends',
  shareTabLink: 'share-tab-link',
  shareTabManage: 'share-tab-manage',
  friendsTabCurrent: 'friends-tab-current',
  friendsTabRequests: 'friends-tab-requests',
  friendsTabDiscover: 'friends-tab-discover',
  notificationBell: 'notification-bell',
  settingsNotifications: 'settings-notifications',
  themeMenu: 'theme-menu',
  profileTheming: 'profile-theming',
} as const;

export type TourTargetId = (typeof TOUR_TARGETS)[keyof typeof TOUR_TARGETS];
