import React from 'react';
import { Comment } from '../../../interfaces/comment.interface';
import { Item } from 'features/items';
import type { CommentContentSegment } from '../../../interfaces/comment-content-segment.type';
import { CommentReactionGroup } from '../../../interfaces/comment-reaction-group.interface';
import type { CommentVisibilityMode } from '../../../interfaces/comment-visibility-mode.type';
import { ListParticipant } from '../../../interfaces/list-participant.interface';

export interface TemplateProps {
  comment: Comment;
  contentSegments: CommentContentSegment[];
  taggedIds: string[];
  isDeleting: boolean;
  items: Item[];
  formatDate: (dateStr?: string) => string;
  onItemTaggedClick?: (itemId: string) => void;
  handleDeleteComment: (commentId: string) => void;
  setDeletingCommentId: (commentId: string | null) => void;
  mentionOnlineByUserId: Record<string, boolean>;
  repliesCount: number;
  toggleReaction?: (commentId: string, reaction: string) => void;
  isAnonymousComment: boolean;
  isSystemComment: boolean;
  isOnline: boolean;
  isListOwnerComment: boolean;
  authorUsername: string | null;
  authorAvatar: string | null;
  authorParticipant?: ListParticipant;
  reactionsMap: Record<string, CommentReactionGroup>;
  isReplying: boolean;
  onReplyToggle: () => void;
  replyInput: React.ReactNode;
  replySlotRef: React.RefObject<HTMLDivElement | null>;
  isExpanded: boolean;
  setIsExpanded: (value: boolean) => void;
  reactionPicker: React.ReactNode;
  nestedReplies: React.ReactNode;
  isOwner: boolean;
  visibilityMode: CommentVisibilityMode;
  visibilityTitle: string;
  isDeleted: boolean;
  isOwnComment: boolean;
  canReply: boolean;
  hasLeftIcons: boolean;
  showLeftRail: boolean;
  showReplyThread: boolean;
  showActionsRow: boolean;
  showRepliesToggle: boolean;
  wrapperClassName: string;
  bubbleClassName: string;
  contentClassName: string;
}
