import { Wishlist, Priority } from 'features/wishlists';
import { Item } from 'features/items';
import { WishlistExportContext } from 'shared/utils/wishlist-export';

export interface HeaderTemplateProps {
  wishlist: Wishlist;
  items: Item[];
  priorities: Priority[];
  isOwner: boolean;
  isPublicGuest?: boolean;
  isExpired: boolean;
  isArchived: boolean;
  isDeactivating: boolean;
  isActivating: boolean;
  isDeleting: boolean;
  confirmAction: 'deactivate' | 'activate' | 'delete' | 'duplicate' | null;
  setConfirmAction: (val: 'deactivate' | 'activate' | 'delete' | 'duplicate' | null) => void;
  handleDeactivateConfirm: () => void;
  handleActivateConfirm: () => void;
  handleDeleteConfirm: () => void;
  saveTitle: (val: string) => Promise<void>;
  saveDate: (val: string) => Promise<void>;
  formatDate: (dateStr: string | null) => string;
  toggleAiEnabled: () => void;
  toggleWebSearchEnabled: () => void;
  toggleManualJobBackground: () => void;
  toggleAutoRollover: () => void;
  canShowAi: boolean;
  canShowWebSearch: boolean;
  isCommentsOpen: boolean;
  setIsCommentsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsShareOpen: (open: boolean) => void;
  canImport: boolean;
  isImportOpen: boolean;
  onImportToggle: () => void;
  onDuplicate: () => void;
  isDuplicating: boolean;
  isEditingTitle: boolean;
  setIsEditingTitle: (val: boolean) => void;
  tempTitle: string;
  setTempTitle: (val: string) => void;
  isEditingDate: boolean;
  setIsEditingDate: (val: boolean) => void;
  tempDate: string;
  setTempDate: (val: string) => void;
  isExportDropdownOpen: boolean;
  setIsExportDropdownOpen: (val: boolean) => void;
  exportRef: React.RefObject<HTMLDivElement | null>;
  isListSettingsOpen: boolean;
  setIsListSettingsOpen: (val: boolean) => void;
  listSettingsRef: React.RefObject<HTMLDivElement | null>;
  exportContext: WishlistExportContext;
  showListSettings: boolean;
  listSettingsReadOnly: boolean;
  showOwnerBadgeRegion: boolean;
  hideOwnerBadgeOnMobile?: boolean;
}
