import type { KeyboardEvent, RefObject } from 'react';
import type { Wishlist, Priority } from 'features/wishlists';
import type { Item } from 'features/items';
import type { ConfirmAction } from '../../../interfaces/confirm-action.type';

export interface TemplateProps {
  wishlist: Wishlist;
  items: Item[];
  priorities: Priority[];
  isOwner: boolean;
  isPublicGuest?: boolean;
  onGoHome: () => void;
  isExpired: boolean;
  isArchived: boolean;
  isDeactivating: boolean;
  isActivating: boolean;
  isDeleting: boolean;
  confirmAction: ConfirmAction;
  confirmMessage: string;
  confirmBannerClassName: string;
  confirmYesBtnClassName: string;
  onConfirmYes: () => void;
  onConfirmNo: () => void;
  formatDate: (dateStr: string | null) => string;
  toggleAiEnabled: () => void;
  toggleWebSearchEnabled: () => void;
  toggleManualJobBackground: () => void;
  toggleAutoRollover: () => void;
  toggleAllowGroupFunds: () => void;
  canShowAi: boolean;
  canShowWebSearch: boolean;
  isCommentsOpen: boolean;
  canImport: boolean;
  isImportOpen: boolean;
  onImportToggle: () => void;
  isDuplicating: boolean;
  duplicateLabel: string;
  isEditingTitle: boolean;
  tempTitle: string;
  onTitleChange: (value: string) => void;
  onTitleBlur: () => void;
  onTitleKeyDown: (event: KeyboardEvent<HTMLInputElement>) => void;
  onStartEditTitle: () => void;
  isEditingDate: boolean;
  tempDate: string;
  onDateChange: (value: string) => void;
  onStartEditDate: () => void;
  isExportDropdownOpen: boolean;
  exportRef: RefObject<HTMLDivElement | null>;
  isListSettingsOpen: boolean;
  listSettingsRef: RefObject<HTMLDivElement | null>;
  showListSettings: boolean;
  listSettingsReadOnly: boolean;
  listSettingsPillClassName: string;
  showOwnerBadgeRegion: boolean;
  ownerBadgeClassName: string;
  ownerDisplayName: string;
  backLinkLabel: string;
  actionsBusy: boolean;
  importPillClassName: string;
  onOpenShare: () => void;
  onToggleComments: () => void;
  onToggleListSettings: () => void;
  onToggleExport: () => void;
  onRequestActivate: () => void;
  onRequestDeactivate: () => void;
  onRequestDelete: () => void;
  onRequestDuplicate: () => void;
  onExportCsv: () => void;
  onExportXlsx: () => void;
  onExportTxt: () => void;
  onExportJson: () => void;
  onExportPdf: () => void;
}
