import type { CollapsibleStripStatus } from 'shared/ui';
import type { TimelineStreamLane } from 'features/jobs/interfaces/job-timeline-view.interface';
import type { Status as DropzoneStatus } from '../../dropzone/interfaces/props.interface';
import type { ImportTimelineStep } from './import-timeline-step.interface';
import type { Mode } from './mode.type';
import type { Phase } from './phase.type';

export interface TemplateProps {
  mode: Mode;
  phase: Phase;
  isExpanded: boolean;
  stripStatus?: CollapsibleStripStatus;
  title: string;
  dropzoneError: string | null;
  errorMessage: string | null;
  uploadPercent: number;
  uploadLabel: string;
  fileName: string | null;
  wishlistTitle: string;
  setWishlistTitle: (value: string) => void;
  timelineSteps: ImportTimelineStep[];
  timelineStreams: TimelineStreamLane[];
  streamsCaption: string | null;
  createLabel: string;
  isBusy: boolean;
  canConfirm: boolean;
  canGrabInfo: boolean;
  grabInfoActive: boolean;
  canOptimizeCategories: boolean;
  optimizeCategoriesActive: boolean;
  allowAi: boolean;
  confirmLabel: string;
  className?: string;
  grabSwitchId: string;
  optimizeSwitchId: string;
  pasteId: string;
  pasteDraft: string;
  setPasteDraft: (value: string) => void;
  onFileSelected: (file: File) => void;
  onPasteText: (text: string) => void;
  onReset: () => void;
  onConfirm: () => void;
  onGrabInfoChange: (checked: boolean) => void;
  onOptimizeCategoriesChange: (checked: boolean) => void;
  aiPanelActive: boolean;
  showDropzone: boolean;
  showPaste: boolean;
  showProgress: boolean;
  showTimeline: boolean;
  showActions: boolean;
  readyHasError: boolean;
  showHeaderMeta: boolean;
  dropzoneStatus: DropzoneStatus;
}
