import type { RefObject } from 'react';
import type { PromptType } from '../../../../../utils/ai-prompt-settings.util';
import type { CustomPackSettings } from '../../metadata-packs/interfaces/custom-pack-settings.interface';
import type { DirectoryPackRow } from '../../metadata-packs/interfaces/directory-pack-row.interface';
import type { PromptCodeEditorHandle } from '../../prompt-code-editor/interfaces/prompt-code-editor-handle.interface';
import type { DirectoryPackListItem } from './directory-pack-list-item.interface';
import type { PromptWorkspaceItem } from './prompt-workspace-item.interface';
import type { WorkspacePromptNavItem } from './workspace-prompt-nav-item.interface';
import type { WorkspaceView } from './workspace-view.interface';

export interface PromptsPacksWorkspaceTemplateProps {
  view: WorkspaceView;
  promptNavItems: readonly WorkspacePromptNavItem[];
  activePrompt: PromptWorkspaceItem | null;
  promptValue: string;
  promptPlaceholder: string;
  resetLabel: string;
  showPopulateHint: boolean;
  promptEditorAriaLabel: string;
  canReset: boolean;
  isAtDefault: boolean;
  directoryActive: boolean;
  directoryListItems: readonly DirectoryPackListItem[];
  selectedPack: DirectoryPackRow | null;
  selectedPackEnabled: boolean;
  selectedPackIsTechnology: boolean;
  fragmentAriaLabel: string;
  enabledCount: number;
  searchQuery: string;
  searchId: string;
  emptyMessage: string;
  isLoading: boolean;
  error: string | null;
  disabled: boolean;
  promptEditorRef: RefObject<PromptCodeEditorHandle | null>;
  editorPack: CustomPackSettings | null;
  editorTakenIds: readonly string[];
  onSelectPrompt: (promptType: PromptType) => void;
  onSelectDirectory: () => void;
  onSelectPack: (packId: string) => void;
  onSearchChange: (query: string) => void;
  onTogglePack: (packId: string, enabled: boolean) => void;
  onPromptChange: (value: string) => void;
  onResetPrompt: () => void;
  onInsertToken: (token: string) => void;
  onCreatePack: () => void;
  onEditPack: (packId: string) => void;
  onDeletePack: (packId: string) => void;
  onApplyEditor: (pack: CustomPackSettings) => void;
  onCancelEditor: () => void;
}
