import type { ItemDescriptionMetadata } from 'shared/interfaces/item-description-metadata.interface';
import type { ClaimBadgeEntry } from '../../../../../../interfaces/claim-badge-entry.interface';
import type { Item } from '../../../../../../interfaces/item.interface';
import type { ItemAudienceUser } from '../../../../../../interfaces/item-audience-user.interface';
import type { ItemSubstitutionOption } from '../../../../../../interfaces/item-substitution.interface';
import type { SubstitutionBrowseOption } from '../../../../../../interfaces/substitution-browse-option.interface';
import type { ColClassResult } from '../../../interfaces/col-class-result.interface';

export interface Props {
  item: Item;
  displayItem: Item;
  canCollaborate: boolean;
  isFavorite: boolean;
  toggleFavorite: () => void;
  hasPriority: boolean;
  leadingCol: ColClassResult;
  selectCol: ColClassResult;
  titleCol: ColClassResult;
  relationsCol: ColClassResult;
  audienceGroupCol: ColClassResult;
  quantityCol: ColClassResult;
  priceCol: ColClassResult;
  reserveSelect: boolean;
  reserveRelations: boolean;
  reserveAudienceGroup: boolean;
  reserveQuantity: boolean;
  isTaggingModeActive?: boolean;
  isTaggedSelection?: boolean;
  onSelectTag?: () => void;
  hasSubstitutionBrowse: boolean;
  substitutionIndex: number;
  substitutionTotal: number;
  substitutionActiveKind: SubstitutionBrowseOption['kind'];
  substitutionActiveOption?: ItemSubstitutionOption;
  badgesAudienceLabel: string | null;
  isPrivate: boolean;
  isLinkedToItems: boolean;
  isRelatedToItems: boolean;
  showSharingAvatars: boolean;
  sharingUsers: ItemAudienceUser[];
  isOwner: boolean;
  showClaimBadge: boolean;
  claimBadgeEntries: ClaimBadgeEntry[];
  suggestedByDisplayName: string;
  showQuantityBadge: boolean;
  metadata: ItemDescriptionMetadata | null;
  primaryPriceLabel: string;
  primaryClassName: string;
  starClassName: string;
  starBtnClassName: string;
  priorityInlineClassName: string;
  mainClassName: string;
  titleClassName: string;
  subBadgesClassName: string;
  metaSubClassName: string;
  linkedIconClassName: string;
  priceValueClassName: string;
}
