/* AUTO-GENERATED by scripts/sync-theme-catalog.ts — do not edit by hand. */
import type { ThemeCatalogEntry } from '../interfaces/theme-catalog-entry.interface';

export const THEME_CATALOG = [
  {
    "id": "default",
    "label": "Linear",
    "category": "standard"
  },
  {
    "id": "neon",
    "label": "Neon",
    "category": "standard"
  },
  {
    "id": "cyberpunk",
    "label": "Cyberpunk",
    "category": "standard"
  },
  {
    "id": "mystic",
    "label": "Mystic",
    "category": "standard"
  },
  {
    "id": "burnt-forest",
    "label": "Burnt Forest",
    "category": "standard"
  },
  {
    "id": "paper",
    "label": "Paper",
    "category": "standard"
  },
  {
    "id": "paper-mario",
    "label": "Paper Mario",
    "category": "standard"
  },
  {
    "id": "retro-80s",
    "label": "80's Retro",
    "category": "standard"
  },
  {
    "id": "pixel",
    "label": "Pixel Art",
    "category": "standard"
  },
  {
    "id": "matrix",
    "label": "Matrix",
    "category": "standard"
  },
  {
    "id": "terminal",
    "label": "Terminal",
    "category": "standard"
  },
  {
    "id": "vaporwave",
    "label": "Vaporwave",
    "category": "standard"
  },
  {
    "id": "arcade",
    "label": "Arcade",
    "category": "standard"
  },
  {
    "id": "valentines",
    "label": "Valentine's Day",
    "category": "holiday",
    "unlockMonth": 1,
    "unlockLastDay": 28
  },
  {
    "id": "st-patricks",
    "label": "St. Patrick's Day",
    "category": "holiday",
    "unlockMonth": 2,
    "unlockLastDay": 31
  },
  {
    "id": "earth-day",
    "label": "Earth Day",
    "category": "holiday",
    "unlockMonth": 3,
    "unlockLastDay": 30
  },
  {
    "id": "independence",
    "label": "4th of July",
    "category": "holiday",
    "unlockMonth": 6,
    "unlockLastDay": 31
  },
  {
    "id": "halloween",
    "label": "Halloween",
    "category": "holiday",
    "unlockMonth": 9,
    "unlockLastDay": 31
  },
  {
    "id": "thanksgiving",
    "label": "Thanksgiving",
    "category": "holiday",
    "unlockMonth": 10,
    "unlockLastDay": 30
  },
  {
    "id": "christmas",
    "label": "Christmas",
    "category": "holiday",
    "unlockMonth": 11,
    "unlockLastDay": 31
  }
] as const satisfies readonly ThemeCatalogEntry[];

export const THEME_IDS = THEME_CATALOG.map((entry) => entry.id);

export const STANDARD_THEME_IDS = THEME_CATALOG
  .filter((entry) => entry.category === 'standard')
  .map((entry) => entry.id);

export const HOLIDAY_THEME_IDS = THEME_CATALOG
  .filter((entry) => entry.category === 'holiday')
  .map((entry) => entry.id);
