export const GUEST_PREVIEW_POLL_INTERVAL_MS = 30_000;
export const GUEST_PREVIEW_REFRESH_DEBOUNCE_MS = 300;
export const GUEST_INVITE_SOCKET_RECONNECT_MS = 3000;
export const GUEST_INVITE_SOCKET_RECONNECT_ERROR_MS = 5000;
