import type { LocalAiModelMode } from 'features/system';
import type { AiDefaultPromptsView } from 'features/system';
import type { SystemModelsProvider } from 'features/system';
import type { CustomPackSettings } from 'features/system';
import type { PromptType } from 'features/system';
import type { AiModelSlot } from 'features/system';
import type { AiConnectionStatus } from 'features/system';

export interface AiSectionProps {
  aiEnabled: boolean;
  setAiEnabled: (value: boolean) => void;
  aiWebSearchEnabled: boolean;
  setAiWebSearchEnabled: (value: boolean) => void;
  aiRateLimitEnabled: boolean;
  setAiRateLimitEnabled: (value: boolean) => void;
  aiImportChunkingEnabled: boolean;
  setAiImportChunkingEnabled: (value: boolean) => void;
  aiImportChunkItemLimit: number;
  setAiImportChunkItemLimit: (value: number) => void;
  aiConnectTimeoutMs: number;
  setAiConnectTimeoutMs: (value: number) => void;
  aiCompletionTimeoutMs: number;
  setAiCompletionTimeoutMs: (value: number) => void;
  aiFastProvider: SystemModelsProvider;
  setAiFastProvider: (value: SystemModelsProvider) => void;
  aiFastEndpoint: string;
  setAiFastEndpoint: (value: string) => void;
  aiFastApiKey: string;
  setAiFastApiKey: (value: string) => void;
  aiFastModel: string;
  setAiFastModel: (value: string) => void;
  aiIntelligentProvider: SystemModelsProvider;
  setAiIntelligentProvider: (value: SystemModelsProvider) => void;
  aiIntelligentEndpoint: string;
  setAiIntelligentEndpoint: (value: string) => void;
  aiIntelligentApiKey: string;
  setAiIntelligentApiKey: (value: string) => void;
  aiIntelligentModel: string;
  setAiIntelligentModel: (value: string) => void;
  aiPrompt: string;
  setAiPrompt: (value: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (value: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (value: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (value: string) => void;
  aiImportPrompt: string;
  setAiImportPrompt: (value: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  showFastAiKey: boolean;
  setShowFastAiKey: (value: boolean) => void;
  showIntelligentAiKey: boolean;
  setShowIntelligentAiKey: (value: boolean) => void;
  openrouterModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  isLoadingModels: boolean;
  companies: string[];
  selectedFastCompany: string;
  setSelectedFastCompany: (value: string) => void;
  selectedIntelligentCompany: string;
  setSelectedIntelligentCompany: (value: string) => void;
  filteredFastModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  filteredIntelligentModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  localFastModels: string[];
  localIntelligentModels: string[];
  localFastModelMode: LocalAiModelMode;
  localIntelligentModelMode: LocalAiModelMode;
  onLocalModelSelection: (slot: AiModelSlot, value: string) => void;
  fastConnectionStatus: AiConnectionStatus;
  fastConnectionMessage: string;
  intelligentConnectionStatus: AiConnectionStatus;
  intelligentConnectionMessage: string;
  onTestAiConnection: (slot: AiModelSlot) => void;
  aiEnabledPackIds: string[];
  onEnabledPackIdsChange: (ids: string[]) => void;
  aiCustomPacks: CustomPackSettings[];
  onCustomPacksChange: (packs: CustomPackSettings[]) => void;
}
