import type { AiConnectionStatus } from 'features/system';
import type { AiDefaultPromptsView } from 'features/system';
import type { AiModelSlot } from 'features/system';
import type { CustomPackSettings } from 'features/system';
import type { LocalAiModelMode } from 'features/system';
import type { PromptType } from 'features/system';
import type { SystemModelOption } from 'features/system';
import type { SystemModelsProvider } from 'features/system';

export interface AiSectionTemplateProps {
  aiEnabled: boolean;
  setAiEnabled: (value: boolean) => void;
  aiWebSearchEnabled: boolean;
  setAiWebSearchEnabled: (value: boolean) => void;
  aiRateLimitEnabled: boolean;
  setAiRateLimitEnabled: (value: boolean) => void;
  aiImportChunkingEnabled: boolean;
  setAiImportChunkingEnabled: (value: boolean) => void;
  aiImportChunkItemLimit: number;
  setAiImportChunkItemLimit: (value: number) => void;
  aiConnectTimeoutMs: number;
  setAiConnectTimeoutMs: (value: number) => void;
  aiCompletionTimeoutMs: number;
  setAiCompletionTimeoutMs: (value: number) => void;
  aiPrompt: string;
  setAiPrompt: (value: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (value: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (value: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (value: string) => void;
  aiImportPrompt: string;
  setAiImportPrompt: (value: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  openrouterModels: SystemModelOption[];
  isLoadingModels: boolean;
  companies: string[];
  onLocalModelSelection: (slot: AiModelSlot, value: string) => void;
  onTestAiConnection: (slot: AiModelSlot) => void;
  aiEnabledPackIds: string[];
  onEnabledPackIdsChange: (ids: string[]) => void;
  aiCustomPacks: CustomPackSettings[];
  onCustomPacksChange: (packs: CustomPackSettings[]) => void;
  connectionSlot: AiModelSlot;
  setConnectionSlot: (slot: AiModelSlot) => void;
  isFastSlot: boolean;
  activeProvider: SystemModelsProvider;
  setActiveProvider: (value: SystemModelsProvider) => void;
  activeEndpoint: string;
  setActiveEndpoint: (value: string) => void;
  activeApiKey: string;
  setActiveApiKey: (value: string) => void;
  showActiveAiKey: boolean;
  setShowActiveAiKey: (value: boolean) => void;
  activeConnectionStatus: AiConnectionStatus;
  activeConnectionMessage: string;
  isTestingAiConnection: boolean;
  localModelSelectDisabled: boolean;
  activeLocalModels: string[];
  showModelPicker: boolean;
  activeModel: string;
  setActiveModel: (value: string) => void;
  activeSelectedCompany: string;
  setActiveSelectedCompany: (value: string) => void;
  activeFilteredModels: SystemModelOption[];
  activeLocalModelMode: LocalAiModelMode;
  modelHelper: string;
}
