import React from 'react';
import { Wishlist, Priority } from 'features/wishlists';
import { Item } from 'features/items';

export interface WishlistDetailTemplateProps {
  wishlist: Wishlist;
  items: Item[];
  priorities: Priority[];
  isOwner: boolean;
  isExpired: boolean;
  isAddOpen: boolean;
  setIsAddOpen: (open: boolean) => void;
  editingItem: Item | null;
  setEditingItem: (item: Item | null) => void;
  setEditingItemDraft: (draft: Partial<Item> | null) => void;
  linkedItemIds: string[];
  setLinkedItemIds: (ids: string[] | ((prev: string[]) => string[])) => void;
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  loadData: () => Promise<void>;
  confirmAction: 'deactivate' | 'delete' | null;
  setConfirmAction: (action: 'deactivate' | 'delete' | null) => void;
  isDeactivating: boolean;
  isDeleting: boolean;
  handleDeactivateConfirm: () => void;
  handleDeleteConfirm: () => void;
  saveTitle: (title: string) => Promise<void>;
  saveDate: (date: string) => Promise<void>;
  toggleRevealSuggestions: () => void;
  formatDate: (dateStr: string | null) => string;
  isCommentsOpen: boolean;
  setIsCommentsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isShareOpen: boolean;
  setIsShareOpen: (open: boolean) => void;
  viewMode: 'full' | 'compact' | 'grid';
  handleSetViewMode: (mode: 'full' | 'compact' | 'grid') => void;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedItem: Item | null;
  setSelectedItemId: (id: string | null) => void;
  selectedItemId: string | null;
  selectedItemPriorityLabel: string | undefined;
  groupedItems: { categoryKey: string; label: string; items: Item[] }[];
  displayItems: Item[];
  handleItemTaggedClick: (itemId: string) => void;
  isTaggingModeActive: boolean;
  setIsTaggingModeActive: (active: boolean) => void;
  taggedItemIds: string[];
  setTaggedItemIds: (ids: string[]) => void;
  handleSelectTag: (itemId: string) => void;
  isLoading: boolean;
}
