import type { ReactNode } from 'react';
import type { Item } from 'features/items';
import type { ListShare } from 'features/wishlists';
import type { LinkingAudienceContext } from 'features/items/interfaces/linking-audience-context.interface';
import type { ItemEnrichJobResult } from 'features/jobs/interfaces/item-enrich-job-result.interface';
import type { SubstitutionDrawerChrome } from 'features/items/interfaces/substitution-drawer-chrome.interface';

export interface TemplateProps {
  isOpen: boolean;
  isDrawerOpen: boolean;
  isView: boolean;
  isEdit: boolean;
  isSubstitutionMode: boolean;
  title: string;
  titleIcon: ReactNode;
  closeIcon: ReactNode;
  closeAriaLabel: string | undefined;
  formItem: Item | null | undefined;
  existingCategories: string[];
  linkableItems: Item[];
  resolvedLinkedItems: Item[];
  resolvedRelatedItems: Item[];
  linkedItemIds: string[];
  setLinkedItemIds: React.Dispatch<React.SetStateAction<string[]>>;
  relatedItemIds: string[];
  setRelatedItemIds: React.Dispatch<React.SetStateAction<string[]>>;
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  isRelatingModeActive: boolean;
  setIsRelatingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  handleLinkingAudienceChange: (context: LinkingAudienceContext) => void;
  isOwner: boolean;
  canCollaborate: boolean;
  listId: string;
  listAiEnabled: boolean;
  listManualJobBackground: boolean;
  canUseWebSearchOnList: boolean;
  canShowAi: boolean;
  listShares: ListShare[];
  onClose: () => void;
  onSuccess: () => void;
  onAutoEnrichStarted?: (result: ItemEnrichJobResult) => void;
  setEditingItemDraft: (draft: Partial<Item> | null) => void;
  loadData: () => void;
  isLoading: boolean;
  isFormDirty: boolean;
  onFormLoadingChange: (loading: boolean) => void;
  onFormDirtyChange: (dirty: boolean) => void;
  onItemTaggedClick?: (itemId: string) => void;
  autoOpenClaimerSubstitutionNonce: number;
  autoOpenClaimerSubstitutionEditNonce: number;
  autoOpenClaimerSubstitutionEditId: string | null;
  substitutionChrome: SubstitutionDrawerChrome | null;
  substitutionExitNonce: number;
  onSubstitutionChromeChange: (chrome: SubstitutionDrawerChrome | null) => void;
  onCopyMarkdown: () => void;
  onDrawerClose: () => void;
  onDismissSubstitution: () => void;
  showAiBadge: boolean;
  showCopyButton: boolean;
  showSuggestionBanner: boolean;
  showViewModeBanner: boolean;
  showSubstitutionBanner: boolean;
}
