import type { ModelsProvider } from './models-provider.type';
import type { CustomPackSettings } from './custom-pack-settings.interface';
import type { AiDefaultPromptsView } from './ai-default-prompts-view.interface';

export interface BackendSettings {
  DbType: 'local' | 'remote';
  DbUrl: string;
  SmtpType: 'local' | 'remote';
  SmtpHost: string;
  SmtpPort: number;
  SmtpUser: string;
  SmtpPass: string;
  SmtpSecure: boolean;
  SmtpFrom: string;
  PublicAppUrl?: string;
  AllowSetup?: boolean;
  OAuthEnabled?: boolean;
  OAuthIssuerUrl?: string;
  OAuthClientId?: string;
  OAuthClientSecret?: string;
  OAuthScopes?: string;
  OAuthButtonText?: string;
  OAuthAutoRegister?: boolean;
  OAuthAutoLaunch?: boolean;
  AiEnabled?: boolean;
  AiWebSearchEnabled?: boolean;
  AiRateLimitEnabled?: boolean;
  AiFastProvider?: ModelsProvider;
  AiFastEndpoint?: string;
  AiFastApiKey?: string;
  AiFastModel?: string;
  AiIntelligentProvider?: ModelsProvider;
  AiIntelligentEndpoint?: string;
  AiIntelligentApiKey?: string;
  AiIntelligentModel?: string;
  AiPrompt?: string;
  AiDescriptionPrompt?: string;
  AiPopulatePrompt?: string;
  AiCategoryPrompt?: string;
  AiImportPrompt?: string;
  AiImportChunkingEnabled?: boolean;
  AiImportChunkItemLimit?: number;
  AiEnabledPackIds?: string[];
  AiCustomPacks?: CustomPackSettings[];
  AiCompletionTimeoutMs?: number;
  AiConnectTimeoutMs?: number;
  ScrapeFetchTimeoutMs?: number;
  ScrapePlaywrightTimeoutMs?: number;
  GrabInfoConcurrency?: number;
  GrabInfoConcurrencyUnlimited?: boolean;
  GrabInfoActiveStreamLimit?: number;
  NtfyEnabled?: boolean;
  NtfyBaseUrl?: string;
  NtfyAuthToken?: string;
  NtfyTopicPrefix?: string;
  WebPushEnabled?: boolean;
  WebPushVapidPublicKey?: string;
  WebPushVapidPrivateKey?: string;
  WebPushSubject?: string;
  FcmEnabled?: boolean;
  FcmProjectId?: string;
  FcmServiceAccountJson?: string;
  AiDefaultPrompts?: AiDefaultPromptsView;
}
