import type { CustomPackSettings } from './custom-pack-settings.interface';
import type { ModelsProvider } from './models-provider.type';

export interface SettingsPayloadInput {
  dbType: 'local' | 'remote';
  dbUrl: string;
  publicAppUrl: string;
  oauthEnabled: boolean;
  oauthIssuerUrl: string;
  oauthClientId: string;
  oauthClientSecret: string;
  oauthButtonText: string;
  oauthAutoRegister: boolean;
  smtpType: 'local' | 'remote';
  smtpHost: string;
  smtpPort: string;
  smtpUser: string;
  smtpPass: string;
  smtpSecure: boolean;
  smtpFrom: string;
  ntfyEnabled: boolean;
  ntfyBaseUrl: string;
  ntfyAuthToken: string;
  ntfyTopicPrefix: string;
  webPushEnabled: boolean;
  webPushVapidPublicKey: string;
  webPushVapidPrivateKey: string;
  webPushSubject: string;
  fcmEnabled: boolean;
  fcmProjectId: string;
  fcmServiceAccountJson: string;
  aiEnabled: boolean;
  aiWebSearchEnabled: boolean;
  aiRateLimitEnabled: boolean;
  aiImportChunkingEnabled: boolean;
  aiImportChunkItemLimit: number;
  aiCompletionTimeoutMs: number;
  aiConnectTimeoutMs: number;
  scrapeFetchTimeoutMs: number;
  scrapePlaywrightTimeoutMs: number;
  grabInfoConcurrency: number;
  grabInfoConcurrencyUnlimited: boolean;
  grabInfoActiveStreamLimit: number;
  aiFastProvider: ModelsProvider;
  aiFastEndpoint: string;
  aiFastApiKey: string;
  aiFastModel: string;
  aiIntelligentProvider: ModelsProvider;
  aiIntelligentEndpoint: string;
  aiIntelligentApiKey: string;
  aiIntelligentModel: string;
  aiPrompt: string;
  aiDescriptionPrompt: string;
  aiPopulatePrompt: string;
  aiCategoryPrompt: string;
  aiImportPrompt: string;
  aiEnabledPackIds: string[];
  aiCustomPacks: CustomPackSettings[];
  allowSetup: boolean;
}
