import { useEffect, useRef, useState } from 'react';
import type { Props } from '../interfaces/props.interface';
import type { TemplateProps } from '../interfaces/template-props.interface';
import type { SubstitutionEditorState } from '../interfaces/substitution-editor-state.type';
import { ADD_ITEM_FORM_ID } from '../constants/form-id.constant';
import { SUBSTITUTION_FORM_ID } from '../../../constants/substitution-form.constant';
import { useItemsSession } from '../../../providers/session';
import { getFriendlyCategoryLabel } from '../../../utils/category-label.util';
import { METADATA_BADGE_EMOJI } from 'shared/constants/metadata-badge-emoji.constant';
import {
  buildLinkingAudienceContext,
  resolveItemSharedWithUserIds,
} from '../../../utils/item-audience.util';
import { useProductFields } from './use-product-fields';
import { usePendingJobs } from './use-pending-jobs';
import { useCategories } from './use-categories';
import { useVariations } from './use-variations';
import { useAudience } from './use-audience';
import { useFieldDefinitions } from './use-field-definitions';
import { useDescriptionPayload } from './use-description-payload';
import { useEnrich } from './use-enrich';
import { useSummarizeNotes } from './use-summarize-notes';
import { useItemHydrate } from './use-item-hydrate';
import { useEditDirty } from './use-edit-dirty';
import { useSubmitItem } from './use-submit-item';
import { useSubstitutions } from './use-substitutions';

export function useForm({
  listId,
  isOwner,
  canCollaborate = isOwner,
  onSuccess,
  existingCategories = [],
  item,
  onItemEnriched,
  onAutoEnrichStarted,
  onDraftChange,
  wishlistItems = [],
  linkedItemIds,
  setLinkedItemIds,
  resolvedLinkedCount,
  relatedItemIds,
  resolvedRelatedCount,
  isLinkingModeActive,
  setIsLinkingModeActive,
  isRelatingModeActive,
  setIsRelatingModeActive,
  onLinkingAudienceChange,
  isOpen,
  listShares = [],
  onLoadingChange,
  onDirtyChange,
  canShowAi = false,
  listAiEnabled = false,
  listManualJobBackground = true,
  canUseWebSearchOnList = false,
  readOnly = false,
  onSubstitutionChromeChange,
  substitutionExitNonce = 0,
  autoOpenClaimerSubstitutionNonce = 0,
  autoOpenClaimerSubstitutionEditNonce = 0,
  autoOpenClaimerSubstitutionEditId = null,
}: Props): TemplateProps {
  const { user } = useItemsSession();
  const canManageItems = canCollaborate;
  const isSuggestion = item?.IsSuggestion ?? !canManageItems;

  const [isAutopopulating, setIsAutopopulating] = useState(false);
  const [isSummarizingNotes, setIsSummarizingNotes] = useState(false);
  const [undoDescription, setUndoDescription] = useState<string | null>(null);

  const [substitutionEditor, setSubstitutionEditor] = useState<SubstitutionEditorState | null>(
    null
  );
  const substitutionEditorRef = useRef<SubstitutionEditorState | null>(null);
  substitutionEditorRef.current = substitutionEditor;
  const [subSaving, setSubSaving] = useState(false);

  const fields = useProductFields({
    canManageItems,
    isSuggestion,
    linkedItemIds,
    setLinkedItemIds,
    isLinkingModeActive,
    setIsLinkingModeActive,
  });

  const jobs = usePendingJobs({
    listId,
    listManualJobBackground,
    onAutoEnrichStarted,
  });

  const audience = useAudience({ listShares });

  const categories = useCategories({
    existingCategories,
    category: fields.category,
    setCategory: fields.setCategory,
    canShowAi,
  });

  const variationUi = useVariations({
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    setVariations: fields.setVariations,
  });

  useEffect(() => {
    onLoadingChange?.(fields.isLoading);
  }, [fields.isLoading, onLoadingChange]);

  useEffect(() => {
    if (!onLinkingAudienceChange) {
      return;
    }
    if (item && fields.loadedItemId !== item.Id) {
      return;
    }
    const audienceSharedWith = resolveItemSharedWithUserIds(
      audience.visibilityMode,
      audience.sharedWithUserIds,
      {
        ownerUserId: user?.Id,
        listShareUserIds: listShares.map((share) => share.UserId),
      }
    );
    onLinkingAudienceChange(
      buildLinkingAudienceContext(audience.visibilityMode, audienceSharedWith, user?.Id)
    );
  }, [
    audience.visibilityMode,
    audience.sharedWithUserIds,
    user?.Id,
    onLinkingAudienceChange,
    item,
    fields.loadedItemId,
    listShares,
  ]);

  const fieldDefs = useFieldDefinitions({
    category: fields.category,
    canShowAi,
    readOnly,
    substitutionEditor,
    substitutionEditorRef,
    item,
    loadedItemId: fields.loadedItemId,
    hasScraped: fields.hasScraped,
    dynamicValues: fields.dynamicValues,
    setDynamicValues: fields.setDynamicValues,
    setCustomFields: fields.setCustomFields,
    loadedMetadataRef: fields.loadedMetadataRef,
    pendingExtractedRef: fields.pendingExtractedRef,
    lastPartitionDefKeysRef: fields.lastPartitionDefKeysRef,
  });

  const payload = useDescriptionPayload({
    definitions: fieldDefs.definitions,
    dynamicValues: fields.dynamicValues,
    isFieldVisible: fieldDefs.isFieldVisible,
    isMultiCount: fields.isMultiCount,
    linkedItemIds,
    relatedItemIds,
    customFields: fields.customFields,
    description: fields.description,
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    otherUsersCanSee: fields.otherUsersCanSee,
    allowSubstitutions: fields.allowSubstitutions,
    photoEntries: fields.photoEntries,
    initialPhotosSnapshotRef: fields.initialPhotosSnapshotRef,
    item,
    isFavorite: fields.isFavorite,
  });

  const enrich = useEnrich({
    listId,
    item,
    linkUrl: fields.linkUrl,
    setLinkUrl: fields.setLinkUrl,
    setWebsiteName: fields.setWebsiteName,
    setName: fields.setName,
    setPrice: fields.setPrice,
    setDescription: fields.setDescription,
    setCategory: fields.setCategory,
    setHasScraped: fields.setHasScraped,
    setShowExtraFields: fields.setShowExtraFields,
    setErrorMsg: fields.setErrorMsg,
    setWarningMsg: fields.setWarningMsg,
    canShowAi,
    isAutopopulating,
    setIsAutopopulating,
    isSummarizingNotes,
    hasScraped: fields.hasScraped,
    sessionCustomCategories: categories.sessionCustomCategories,
    setSessionCustomCategories: categories.setSessionCustomCategories,
    deletedCategories: categories.deletedCategories,
    setDeletedCategories: categories.setDeletedCategories,
    setAiCategoryPrimary: categories.setAiCategoryPrimary,
    setAiCategoryAlternatives: categories.setAiCategoryAlternatives,
    pendingExtractedRef: fields.pendingExtractedRef,
    applyExtractedCustomFields: fieldDefs.applyExtractedCustomFields,
    substitutionEditorRef,
    pendingJobRef: jobs.pendingJobRef,
    startJobRun: jobs.startJobRun,
    onItemEnriched,
  });

  const summarize = useSummarizeNotes({
    canShowAi,
    listAiEnabled,
    listId,
    item,
    name: fields.name,
    description: fields.description,
    setDescription: fields.setDescription,
    linkUrl: fields.linkUrl,
    websiteName: fields.websiteName,
    price: fields.price,
    category: fields.category,
    priorityWeight: fields.priorityWeight,
    customFields: fields.customFields,
    definitions: fieldDefs.definitions,
    dynamicValues: fields.dynamicValues,
    isFieldVisible: fieldDefs.isFieldVisible,
    isMultiCount: fields.isMultiCount,
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    isAutopopulating,
    isSummarizingNotes,
    setIsSummarizingNotes,
    undoDescription,
    setUndoDescription,
    setErrorMsg: fields.setErrorMsg,
    setWarningMsg: fields.setWarningMsg,
    pendingJobRef: jobs.pendingJobRef,
    startJobRun: jobs.startJobRun,
  });

  useItemHydrate({
    item,
    isOpen,
    canManageItems,
    canShowAi,
    readOnly,
    listShares,
    definitions: fieldDefs.definitions,
    substitutionEditorRef,
    runAbandonPendingJob: jobs.runAbandonPendingJob,
    jobRunRef: jobs.jobRunRef,
    pendingJobRef: jobs.pendingJobRef,
    resetOptionalFields: fields.resetOptionalFields,
    clearAiCategories: categories.clearAiCategories,
    setName: fields.setName,
    setDescription: fields.setDescription,
    setPriorityWeight: fields.setPriorityWeight,
    setIsHiddenIdea: fields.setIsHiddenIdea,
    setSharedWithUserIds: audience.setSharedWithUserIds,
    setVisibilityMode: audience.setVisibilityMode,
    setLinkUrl: fields.setLinkUrl,
    setWebsiteName: fields.setWebsiteName,
    setCategory: fields.setCategory,
    setPrice: fields.setPrice,
    setIsFavorite: fields.setIsFavorite,
    setAllowSubstitutions: fields.setAllowSubstitutions,
    setSubstitutionOptions: fields.setSubstitutionOptions,
    setPhotoEntries: fields.setPhotoEntries,
    setPhotoError: fields.setPhotoError,
    setLoadedItemId: fields.setLoadedItemId,
    setHasScraped: fields.setHasScraped,
    setUndoDescription,
    setIsSummarizingNotes,
    setIsAutopopulating,
    setErrorMsg: fields.setErrorMsg,
    setWarningMsg: fields.setWarningMsg,
    setOtherUsersCanSee: fields.setOtherUsersCanSee,
    setDesiredQuantityState: fields.setDesiredQuantityState,
    setVariations: fields.setVariations,
    setShowExtraFields: fields.setShowExtraFields,
    setCustomFields: fields.setCustomFields,
    setDynamicValues: fields.setDynamicValues,
    initialPhotosSnapshotRef: fields.initialPhotosSnapshotRef,
    loadedMetadataRef: fields.loadedMetadataRef,
  });

  const dirty = useEditDirty({
    item,
    loadedItemId: fields.loadedItemId,
    readOnly,
    substitutionEditor,
    onDirtyChange,
    onDraftChange,
    name: fields.name,
    description: fields.description,
    priorityWeight: fields.priorityWeight,
    category: fields.category,
    linkUrl: fields.linkUrl,
    websiteName: fields.websiteName,
    price: fields.price,
    isFavorite: fields.isFavorite,
    customFields: fields.customFields,
    dynamicValues: fields.dynamicValues,
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    visibilityMode: audience.visibilityMode,
    sharedWithUserIds: audience.sharedWithUserIds,
    otherUsersCanSee: fields.otherUsersCanSee,
    allowSubstitutions: fields.allowSubstitutions,
    isHiddenIdea: fields.isHiddenIdea,
    linkedItemIds,
    relatedItemIds,
    photoEntries: fields.photoEntries,
    listShares,
    userId: user?.Id,
    canManageItems,
    isMultiCount: fields.isMultiCount,
    buildDescriptionPayload: payload.buildDescriptionPayload,
  });

  const submit = useSubmitItem({
    readOnly,
    item,
    isEditDirty: dirty.isEditDirty,
    name: fields.name,
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    isMultiCount: fields.isMultiCount,
    visibilityMode: audience.visibilityMode,
    sharedWithUserIds: audience.sharedWithUserIds,
    hasIncompleteCustomFields: fields.hasIncompleteCustomFields,
    listShares,
    userId: user?.Id,
    userFirstName: user?.FirstName,
    userLastName: user?.LastName,
    userUsername: user?.Username,
    linkedItemIds,
    relatedItemIds,
    wishlistItems,
    listId,
    category: fields.category,
    canManageItems,
    claimOnCreate: fields.claimOnCreate,
    isHiddenIdea: fields.isHiddenIdea,
    isFavorite: fields.isFavorite,
    priorityWeight: fields.priorityWeight,
    linkUrl: fields.linkUrl,
    price: fields.price,
    websiteName: fields.websiteName,
    buildDescriptionPayload: payload.buildDescriptionPayload,
    setIsLoading: fields.setIsLoading,
    setErrorMsg: fields.setErrorMsg,
    setWarningMsg: fields.setWarningMsg,
    setShowExtraFields: fields.setShowExtraFields,
    setName: fields.setName,
    setDescription: fields.setDescription,
    setPriorityWeight: fields.setPriorityWeight,
    setIsHiddenIdea: fields.setIsHiddenIdea,
    setSharedWithUserIds: audience.setSharedWithUserIds,
    setLinkUrl: fields.setLinkUrl,
    setWebsiteName: fields.setWebsiteName,
    setCategory: fields.setCategory,
    clearAiCategories: categories.clearAiCategories,
    setPrice: fields.setPrice,
    setIsFavorite: fields.setIsFavorite,
    setCustomFields: fields.setCustomFields,
    setEditingCustomFieldNameId: fields.setEditingCustomFieldNameId,
    setPhotoEntries: fields.setPhotoEntries,
    setPhotoError: fields.setPhotoError,
    initialPhotosSnapshotRef: fields.initialPhotosSnapshotRef,
    onSuccess,
  });

  const subs = useSubstitutions({
    item,
    canManageItems,
    canShowAi,
    userId: user?.Id,
    userFirstName: user?.FirstName,
    userLastName: user?.LastName,
    userUsername: user?.Username,
    substitutionExitNonce,
    autoOpenClaimerSubstitutionNonce,
    autoOpenClaimerSubstitutionEditNonce,
    autoOpenClaimerSubstitutionEditId,
    onSubstitutionChromeChange,
    onSuccess,
    onItemEnriched,
    definitions: fieldDefs.definitions,
    buildSubstitutionMetadata: payload.buildSubstitutionMetadata,
    name: fields.name,
    description: fields.description,
    priorityWeight: fields.priorityWeight,
    linkUrl: fields.linkUrl,
    websiteName: fields.websiteName,
    category: fields.category,
    price: fields.price,
    isFavorite: fields.isFavorite,
    desiredQuantity: fields.desiredQuantity,
    variations: fields.variations,
    customFields: fields.customFields,
    dynamicValues: fields.dynamicValues,
    showExtraFields: fields.showExtraFields,
    photoEntries: fields.photoEntries,
    photoError: fields.photoError,
    otherUsersCanSee: fields.otherUsersCanSee,
    isHiddenIdea: fields.isHiddenIdea,
    claimOnCreate: fields.claimOnCreate,
    allowSubstitutions: fields.allowSubstitutions,
    substitutionOptions: fields.substitutionOptions,
    errorMsg: fields.errorMsg,
    hasScraped: fields.hasScraped,
    setName: fields.setName,
    setDescription: fields.setDescription,
    setPriorityWeight: fields.setPriorityWeight,
    setLinkUrl: fields.setLinkUrl,
    setWebsiteName: fields.setWebsiteName,
    setCategory: fields.setCategory,
    setPrice: fields.setPrice,
    setIsFavorite: fields.setIsFavorite,
    setDesiredQuantityState: fields.setDesiredQuantityState,
    setVariations: fields.setVariations,
    setCustomFields: fields.setCustomFields,
    setDynamicValues: fields.setDynamicValues,
    setShowExtraFields: fields.setShowExtraFields,
    setPhotoEntries: fields.setPhotoEntries,
    setPhotoError: fields.setPhotoError,
    setOtherUsersCanSee: fields.setOtherUsersCanSee,
    setIsHiddenIdea: fields.setIsHiddenIdea,
    setClaimOnCreate: fields.setClaimOnCreate,
    setAllowSubstitutions: fields.setAllowSubstitutions,
    setSubstitutionOptions: fields.setSubstitutionOptions,
    setErrorMsg: fields.setErrorMsg,
    setHasScraped: fields.setHasScraped,
    setUndoDescription,
    resetOptionalFields: fields.resetOptionalFields,
    clearAiCategories: categories.clearAiCategories,
    initialPhotosSnapshotRef: fields.initialPhotosSnapshotRef,
    loadedMetadataRef: fields.loadedMetadataRef,
    substitutionEditor,
    setSubstitutionEditor,
    substitutionEditorRef,
    subSaving,
    setSubSaving,
  });

  return {
    name: fields.name,
    setName: fields.setName,
    description: fields.description,
    setDescription: fields.setDescription,
    priorityWeight: fields.priorityWeight,
    setPriorityWeight: fields.setPriorityWeight,
    isHiddenIdea: fields.isHiddenIdea,
    setIsHiddenIdea: fields.setIsHiddenIdea,
    canCollaborate: canManageItems,
    isLoading: fields.isLoading || subs.subSaving,
    errorMsg: fields.errorMsg,
    warningMsg: fields.warningMsg,
    handleSubmit: substitutionEditor ? subs.handleSubstitutionSubmit : submit.handleSubmit,
    formId: substitutionEditor ? SUBSTITUTION_FORM_ID : ADD_ITEM_FORM_ID,
    isSubstitutionSurface: !!substitutionEditor,
    linkUrl: fields.linkUrl,
    setLinkUrl: fields.setLinkUrl,
    linkCopied: fields.linkCopied,
    onCopyLink: fields.onCopyLink,
    websiteName: fields.websiteName,
    setWebsiteName: fields.setWebsiteName,
    category: fields.category,
    setCategory: fields.setCategory,
    price: fields.price,
    setPrice: fields.setPrice,
    isFavorite: fields.isFavorite,
    setIsFavorite: fields.setIsFavorite,
    isAutopopulating: enrich.isAutopopulating,
    handleScrapeClick: enrich.handleScrapeClick,
    canUseWebSearchOnList,
    customFields: fields.customFields,
    handleAddCustomField: fields.handleAddCustomField,
    handleRemoveCustomField: fields.handleRemoveCustomField,
    handleUpdateCustomField: fields.handleUpdateCustomField,
    editingCustomFieldNameId: fields.editingCustomFieldNameId,
    onStartEditCustomFieldName: fields.setEditingCustomFieldNameId,
    onFinishEditCustomFieldName: () => fields.setEditingCustomFieldNameId(null),
    hasIncompleteCustomFields: fields.hasIncompleteCustomFields,
    showExtraFields: fields.showExtraFields,
    setShowExtraFields: fields.setShowExtraFields,
    renderedCategories: categories.renderedCategories,
    aiCategoryChips: categories.aiCategoryChips,
    aiCategoryIds: categories.aiCategoryIds,
    isAddingCustom: categories.isAddingCustom,
    setIsAddingCustom: categories.setIsAddingCustom,
    newCustomInput: categories.newCustomInput,
    setNewCustomInput: categories.setNewCustomInput,
    handleDeleteCustomCategory: categories.handleDeleteCustomCategory,
    handleAddCustomCategory: categories.handleAddCustomCategory,
    isScrapeButtonPulsing: enrich.isScrapeButtonPulsing,
    isEdit: !!item,
    definitions: fieldDefs.definitions,
    dynamicValues: fields.dynamicValues,
    isFieldVisible: fieldDefs.isFieldVisible,
    handleUpdateDynamicValue: fields.handleUpdateDynamicValue,
    currentUserId: user?.Id,
    otherUsersCanSee: fields.otherUsersCanSee,
    setOtherUsersCanSee: fields.setOtherUsersCanSee,
    claimOnCreate: fields.claimOnCreate,
    setClaimOnCreate: fields.setClaimOnCreate,
    isMultiCount: fields.isMultiCount,
    isSuggestion,
    desiredQuantity: fields.desiredQuantity,
    setDesiredQuantity: fields.setDesiredQuantity,
    variations: fields.variations,
    setVariations: fields.setVariations,
    linkedItemIds,
    resolvedLinkedCount,
    relatedItemIds,
    resolvedRelatedCount,
    wishlistItems,
    itemId: item?.Id,
    isLinkingModeActive,
    setIsLinkingModeActive: fields.handleSetIsLinkingModeActive,
    isRelatingModeActive,
    setIsRelatingModeActive,
    getFriendlyCategoryLabel,
    showFieldDefinitions: fieldDefs.showFieldDefinitions,
    varName: variationUi.varName,
    setVarName: variationUi.setVarName,
    varQty: variationUi.varQty,
    setVarQty: variationUi.setVarQty,
    variationQtyMax:
      variationUi.variationQtyMax && variationUi.variationQtyMax > 0
        ? variationUi.variationQtyMax
        : undefined,
    variationQtyDisabled: variationUi.variationQtyDisabled,
    variationQtyAllowInfinity: variationUi.variationQtyAllowInfinity,
    varError: variationUi.varError,
    handleAddVariation: variationUi.handleAddVariation,
    listShares,
    sharedWithUserIds: audience.sharedWithUserIds,
    setSharedWithUserIds: audience.setSharedWithUserIds,
    visibilityMode: audience.visibilityMode,
    onVisibilityModeChange: audience.handleVisibilityModeChange,
    canShowAi,
    canSummarizeNotes: summarize.canSummarizeNotes,
    isSummarizingNotes: summarize.isSummarizingNotes,
    canUndoSummarize: summarize.undoDescription !== null,
    onSummarizeNotes: summarize.handleSummarizeNotes,
    onUndoSummarize: summarize.handleUndoSummarize,
    showPhotoGallery: user?.Policy?.CanUploadImages !== false || fields.photoEntries.length > 0,
    photoEntries: fields.photoEntries,
    onPhotoEntriesChange: fields.setPhotoEntries,
    photoError: fields.photoError,
    onPhotoError: fields.setPhotoError,
    readOnly: readOnly && !substitutionEditor,
    readOnlyMetadataPredefined: fieldDefs.readOnlyMetadataDisplay.predefinedDisplayEntries,
    readOnlyMetadataUserDefined: fieldDefs.readOnlyMetadataDisplay.userDefinedEntries,
    hasReadOnlyMetadata: fieldDefs.hasReadOnlyMetadata,
    metadataBadgeEmoji: METADATA_BADGE_EMOJI,
    allowSubstitutions: fields.allowSubstitutions,
    setAllowSubstitutions: fields.setAllowSubstitutions,
    substitutionOptions: fields.substitutionOptions,
    onOpenCreateSubstitution: subs.openCreateSubstitution,
    onOpenEditSubstitution: subs.openEditSubstitution,
    onDeleteOwnerSubstitution: subs.handleDeleteOwnerSubstitution,
    onReorderOwnerSubstitutions: subs.handleReorderOwnerSubstitutions,
    substitutionEditor,
  };
}
