/**
 * Syncs theming-engine dist/js/theme-catalog.json into src/core/theme.
 * Run after `bun run build` in ../theming-engine (e.g. giftistry-bun predev).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SOURCE = join(ROOT, '../theming-engine/dist/js/theme-catalog.json');
const OUT = join(ROOT, 'src/core/theme/constants/theme-catalog.constant.ts');

interface CatalogEntry {
  id: string;
  label: string;
  category: 'standard' | 'holiday';
  unlockMonth?: number;
  unlockLastDay?: number;
}

if (!existsSync(SOURCE)) {
  console.error(
    `[sync-theme-catalog] Missing ${SOURCE}. Run \`bun run build\` in theming-engine first.`,
  );
  process.exit(1);
}

const catalog = JSON.parse(readFileSync(SOURCE, 'utf8')) as CatalogEntry[];
if (!Array.isArray(catalog) || catalog.length === 0) {
  console.error('[sync-theme-catalog] theme-catalog.json is empty or invalid.');
  process.exit(1);
}

const serialized = JSON.stringify(catalog, null, 2);
const contents = `/* AUTO-GENERATED by scripts/sync-theme-catalog.ts — do not edit by hand. */
import type { ThemeCatalogEntry } from '../interfaces/theme-catalog-entry.interface';

export const THEME_CATALOG = ${serialized} as const satisfies readonly ThemeCatalogEntry[];

export const THEME_IDS = THEME_CATALOG.map((entry) => entry.id);

export const STANDARD_THEME_IDS = THEME_CATALOG
  .filter((entry) => entry.category === 'standard')
  .map((entry) => entry.id);

export const HOLIDAY_THEME_IDS = THEME_CATALOG
  .filter((entry) => entry.category === 'holiday')
  .map((entry) => entry.id);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, contents);
console.log(`[sync-theme-catalog] Wrote ${catalog.length} themes → ${OUT}`);
