import React from 'react';
import { Wishlist, Priority } from 'features/wishlists';
import { Item, type ImportStripHandle, type ItemActions } from 'features/items';
import { ItemViewMode } from '../../../../features/items/types/item-view-mode.type';
import { ListShare } from 'features/wishlists/interfaces/list-share.interface';
import { LinkingAudienceContext } from 'features/items/utils/item-audience.util';
import type { BackgroundJobView, ItemEnrichJobResult } from 'features/jobs';

export interface WishlistDetailTemplateProps {
  isWishlistLoading: boolean;
  wishlistError: string | null;
  wishlist: Wishlist | null;
  items: Item[];
  priorities: Priority[];
  isOwner: boolean;
  canCollaborate: boolean;
  isExpired: boolean;
  isArchived: boolean;
  isAddOpen: boolean;
  setIsAddOpen: (open: boolean) => void;
  openAddDrawer: () => void;
  isAutoAddOpen: boolean;
  openAutoAdd: () => void;
  closeAutoAdd: () => void;
  onAutoAddStarted: (result: ItemEnrichJobResult) => void;
  enrichingItemIds: Set<string>;
  editingItem: Item | null;
  setEditingItem: (item: Item | null) => void;
  openItemEditor: (item: Item) => void;
  setEditingItemDraft: (draft: Partial<Item> | null) => void;
  linkedItemIds: string[];
  setLinkedItemIds: (ids: string[] | ((prev: string[]) => string[])) => void;
  relatedItemIds: string[];
  setRelatedItemIds: (ids: string[] | ((prev: string[]) => string[])) => void;
  linkableItems: Item[];
  resolvedLinkedItems: Item[];
  resolvedRelatedItems: Item[];
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  isRelatingModeActive: boolean;
  setIsRelatingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  /** True below 75rem where the add drawer overlays the list instead of shifting layout. */
  doesAddSidebarOverlayList: boolean;
  handleLinkingAudienceChange: (context: LinkingAudienceContext) => void;
  isItemLinkCompatible: (item: Item) => boolean;
  handleLinkItemToggle: (itemId: string) => void;
  handleRelateItemToggle: (itemId: string) => void;
  loadData: () => Promise<void>;
  reloadListContent: () => Promise<void>;
  onItemsChange: () => void | Promise<void>;
  itemActions: ItemActions;
  confirmAction: 'deactivate' | 'activate' | 'delete' | null;
  setConfirmAction: (action: 'deactivate' | 'activate' | 'delete' | null) => void;
  isDeactivating: boolean;
  isActivating: boolean;
  isDeleting: boolean;
  handleDeactivateConfirm: () => void;
  handleActivateConfirm: () => void;
  handleDeleteConfirm: () => void;
  saveTitle: (title: string) => Promise<void>;
  saveDate: (date: string) => Promise<void>;
  toggleRevealSuggestions: () => void;
  toggleAiEnabled?: () => void;
  toggleWebSearchEnabled?: () => void;
  toggleManualJobBackground?: () => void;
  canUseWebSearchOnList?: boolean;
  formatDate: (dateStr: string | null) => string;
  isCommentsOpen: boolean;
  setIsCommentsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isShareOpen: boolean;
  setIsShareOpen: (open: boolean) => void;
  isImportOpen: boolean;
  setIsImportOpen: (open: boolean) => void;
  importStripRef: React.RefObject<ImportStripHandle | null>;
  viewMode: ItemViewMode;
  handleSetViewMode: (mode: ItemViewMode) => void;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedItem: Item | null;
  setSelectedItemId: (id: string | null) => void;
  selectedItemId: string | null;
  selectedItemPriorityLabel: string | undefined;
  groupedItems: { categoryKey: string; label: string; items: Item[] }[];
  collapsedGroupKeys: Set<string>;
  toggleGroupCollapsed: (categoryKey: string) => void;
  displayItems: Item[];
  listShares: ListShare[];
  handleItemTaggedClick: (itemId: string) => void;
  isTaggingModeActive: boolean;
  setIsTaggingModeActive: (active: boolean) => void;
  taggedItemIds: string[];
  setTaggedItemIds: (ids: string[]) => void;
  isReplyTaggingModeActive: boolean;
  setIsReplyTaggingModeActive: (active: boolean) => void;
  replyTaggedItemIds: string[];
  setReplyTaggedItemIds: (ids: string[]) => void;
  handleSelectTag: (itemId: string) => void;
  handleSelectReplyTag: (itemId: string) => void;
  isLoading: boolean;
  activeJob: BackgroundJobView | null;
  isCancellingJob: boolean;
  onCancelJob: () => void;
  canShowAi?: boolean;
}
