import type { KeyboardEvent, MouseEvent } from 'react';
import type { CompactCategoryColumnPresence } from '../../../../interfaces/compact-category-column-presence.interface';
import type { ClaimBadgeEntry } from '../../../../interfaces/claim-badge-entry.interface';
import type { ItemAudienceUser } from '../../../../interfaces/item-audience-user.interface';
import type { ItemLink } from '../../../../interfaces/item-link.interface';
import type { ItemViewProps } from '../../../../interfaces/item-view-props.interface';
import type { ColClassResult } from './col-class-result.interface';

export interface TemplateProps extends ItemViewProps {
  showSharingAvatars: boolean;
  columnPresence: CompactCategoryColumnPresence;
  isSyncEnabled: boolean;
  rootClassName: string;
  switcherClassName: string;
  innerClassName: string;
  bodyClassName: string;
  primaryClassName: string;
  starClassName: string;
  starBtnClassName: string;
  priorityInlineClassName: string;
  mainClassName: string;
  titleClassName: string;
  subBadgesClassName: string;
  metaSubClassName: string;
  linkedIconClassName: string;
  priceValueClassName: string;
  secondaryClassName: string;
  rowClassName: string;
  actionsClassName: string;
  claimActionsClassName: string;
  trailingClassName: string;
  confirmButtonsClassName: string;
  claimFormPanelClassName: string;
  actionBtnClassName: string;
  actionBtnClaimClassName: string;
  actionBtnDangerClassName: string;
  actionBtnClaimDangerClassName: string;
  actionBtnPrimaryClassName: string;
  actionBtnConfirmClassName: string;
  actionBtnConfirmPrimaryClassName: string;
  onRootMouseEnter: () => void;
  onRootMouseLeave: () => void;
  isLinkedToItems: boolean;
  isRelatedToItems: boolean;
  primaryLink: ItemLink | undefined;
  primaryPrice: number | null | undefined;
  primaryPriceLabel: string;
  primaryImageUrl: string | null;
  primaryLinkTitle: string;
  primaryLinkAriaLabel: string;
  sharingUsers: ItemAudienceUser[];
  claimBadgeEntries: ClaimBadgeEntry[];
  showClaimBadge: boolean;
  hasSubstitutionBrowse: boolean;
  substitutionTotal: number;
  substitutionIndex: number;
  showCompactActions: boolean;
  hasPriority: boolean;
  showRelationsIcons: boolean;
  reserveSelect: boolean;
  reserveRelations: boolean;
  reserveAudienceGroup: boolean;
  reserveFunding: boolean;
  reserveTrailing: boolean;
  reserveQuantity: boolean;
  showQuantityBadge: boolean;
  showSecondaryRow: boolean;
  hasFundingContent: boolean;
  hasExpandableContent: boolean;
  showGuestClaimActions: boolean;
  showWideClaimActionPair: boolean;
  useSyncedClaimActionWidth: boolean;
  useSyncedConfirmButtons: boolean;
  spanClaimActionWidth: boolean;
  showClaimFormWithActions: boolean;
  showClaimFormPrompt: boolean;
  showDeleteConfirmPanel: boolean;
  showExpanded: boolean;
  showExpandedMetadata: boolean;
  canShowEditActions: boolean;
  showLinkedClaimTags: boolean;
  claimPrompt: string | undefined;
  claimConfirmLabel: string;
  unclaimLabel: string;
  linkedClaimPeerIds: string[];
  badgesAudienceLabel: string | null;
  suggestedByDisplayName: string;
  leadingCol: ColClassResult;
  selectCol: ColClassResult;
  titleCol: ColClassResult;
  relationsCol: ColClassResult;
  audienceGroupCol: ColClassResult;
  quantityCol: ColClassResult;
  priceCol: ColClassResult;
  fundingCol: ColClassResult;
  trailingCol: ColClassResult;
  onCompactRowClick: (e: MouseEvent) => void;
  onCompactRowKeyDown: ((e: KeyboardEvent) => void) | undefined;
  compactRowRole: 'button' | undefined;
  compactRowTabIndex: 0 | undefined;
}
