import type React from 'react';
import type { FieldDefinition } from '../../../interfaces/field-definition.interface';
import type { ListShare } from 'features/wishlists/interfaces/list-share.interface';
import type { CustomFieldRow } from '../../../interfaces/custom-field-row.interface';
import type { ItemPhotoGalleryEntry } from '../../photo-gallery/interfaces/item-photo-gallery-props.interface';
import type { ItemSubstitutionOption } from '../../../interfaces/item-substitution.interface';
import type { SubstitutionEditorState } from './substitution-editor-state.type';
import type { Item } from '../../../interfaces/item.interface';

export interface TemplateProps {
  name: string;
  setName: (val: string) => void;
  description: string;
  setDescription: (val: string) => void;
  priorityWeight: string;
  setPriorityWeight: (val: string) => void;
  isHiddenIdea: boolean;
  setIsHiddenIdea: (val: boolean) => void;
  canCollaborate: boolean;
  isLoading: boolean;
  errorMsg: string | null;
  warningMsg: string | null;
  handleSubmit: (e: React.SyntheticEvent) => void;
  linkUrl: string;
  setLinkUrl: (val: string) => void;
  websiteName: string;
  setWebsiteName: (val: string) => void;
  category: string;
  setCategory: (val: string) => void;
  price: string;
  setPrice: (val: string) => void;
  isFavorite: boolean;
  setIsFavorite: (val: boolean) => void;
  isAutopopulating: boolean;
  handleScrapeClick: (e: React.MouseEvent) => void;
  canUseWebSearchOnList?: boolean;
  customFields: CustomFieldRow[];
  handleAddCustomField: () => void;
  handleRemoveCustomField: (id: string) => void;
  handleUpdateCustomField: (id: string, key: 'name' | 'value', value: string) => void;
  editingCustomFieldNameId: string | null;
  onStartEditCustomFieldName: (id: string) => void;
  onFinishEditCustomFieldName: () => void;
  hasIncompleteCustomFields: boolean;
  showExtraFields: boolean;
  setShowExtraFields: (val: boolean) => void;
  renderedCategories: { id: string; label: string; isCustom?: boolean; isFromList?: boolean }[];
  aiCategoryChips: Array<{ id: string; label: string; variant: 'primary' | 'suggestion' }>;
  aiCategoryIds: Set<string>;
  isAddingCustom: boolean;
  setIsAddingCustom: (val: boolean) => void;
  newCustomInput: string;
  setNewCustomInput: (val: string) => void;
  handleAddCustomCategory: () => void;
  handleDeleteCustomCategory: (catId: string) => void;
  isScrapeButtonPulsing: boolean;
  isEdit?: boolean;
  definitions: FieldDefinition[];
  dynamicValues: Record<string, string>;
  isFieldVisible: (def: FieldDefinition) => boolean;
  handleUpdateDynamicValue: (key: string, val: string) => void;
  currentUserId?: string;
  otherUsersCanSee: boolean;
  setOtherUsersCanSee: (val: boolean) => void;
  claimOnCreate: boolean;
  setClaimOnCreate: (val: boolean) => void;
  isMultiCount: boolean;
  isSuggestion: boolean;
  desiredQuantity: number | '';
  setDesiredQuantity: (val: number | '') => void;
  variations: { name: string; quantity: number }[];
  setVariations: React.Dispatch<React.SetStateAction<{ name: string; quantity: number }[]>>;
  linkedItemIds: string[];
  resolvedLinkedCount: number;
  relatedItemIds: string[];
  resolvedRelatedCount: number;
  wishlistItems?: Item[];
  itemId?: string;
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  isRelatingModeActive: boolean;
  setIsRelatingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  getFriendlyCategoryLabel: (id: string) => string;
  showFieldDefinitions: boolean;
  varName: string;
  setVarName: (val: string) => void;
  varQty: number;
  setVarQty: (val: number) => void;
  variationQtyMax?: number;
  variationQtyDisabled?: boolean;
  variationQtyAllowInfinity?: boolean;
  varError: string | null;
  handleAddVariation: () => void;
  listShares: ListShare[];
  sharedWithUserIds: string[];
  setSharedWithUserIds: (userIds: string[]) => void;
  visibilityMode: 'everyone' | 'restricted' | 'private';
  onVisibilityModeChange: (mode: 'everyone' | 'restricted' | 'private') => void;
  canShowAi?: boolean;
  canSummarizeNotes: boolean;
  isSummarizingNotes: boolean;
  canUndoSummarize: boolean;
  onSummarizeNotes: () => void;
  onUndoSummarize: () => void;
  showPhotoGallery: boolean;
  photoEntries: ItemPhotoGalleryEntry[];
  onPhotoEntriesChange: (photos: ItemPhotoGalleryEntry[]) => void;
  photoError: string | null;
  onPhotoError: (message: string | null) => void;
  readOnly?: boolean;
  allowSubstitutions: boolean;
  setAllowSubstitutions: (value: boolean) => void;
  substitutionOptions: ItemSubstitutionOption[];
  onOpenCreateSubstitution: () => void;
  onOpenEditSubstitution: (option: ItemSubstitutionOption) => void;
  onDeleteOwnerSubstitution: (substitutionId: string) => Promise<void>;
  onReorderOwnerSubstitutions: (orderedIds: string[]) => Promise<void>;
  /** When set, form shows product fields for a substitution child (hides manager/audience/links). */
  substitutionEditor: SubstitutionEditorState | null;
  isSubstitutionSurface: boolean;
  formId: string;
  readOnlyMetadataPredefined: { label: string; value: string }[];
  readOnlyMetadataUserDefined: { name: string; value: string }[];
  hasReadOnlyMetadata: boolean;
  metadataBadgeEmoji: Record<string, string>;
  linkCopied: boolean;
  onCopyLink: () => void;
}
