import { LocalAiModelMode } from './local-ai-model.interface';
import type { AiDefaultPromptsView } from './backend-settings.interface';
import type { PromptType } from '../utils/ai-prompt-settings.util';

export interface AiSectionProps {
  aiEnabled: boolean;
  setAiEnabled: (value: boolean) => void;
  aiProvider: 'gemini' | 'openai' | 'anthropic' | 'local' | 'openrouter';
  setAiProvider: (value: 'gemini' | 'openai' | 'anthropic' | 'local' | 'openrouter') => void;
  aiApiKey: string;
  setAiApiKey: (value: string) => void;
  aiModel: string;
  setAiModel: (value: string) => void;
  aiPrompt: string;
  setAiPrompt: (value: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (value: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (value: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (value: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  aiEndpoint: string;
  setAiEndpoint: (value: string) => void;
  showAiKey: boolean;
  setShowAiKey: (value: boolean) => void;
  openrouterModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  isLoadingModels: boolean;
  companies: string[];
  selectedCompany: string;
  setSelectedCompany: (value: string) => void;
  filteredModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  localAiModels: string[];
  localModelMode: LocalAiModelMode;
  onLocalModelSelection: (value: string) => void;
  aiConnectionStatus: 'idle' | 'checking' | 'success' | 'error';
  aiConnectionMessage: string;
  onTestAiConnection: () => void;
  isTestingAiConnection: boolean;
}
