import { LocalAiModelMode } from './local-ai-model.interface';
import type { AiDefaultPromptsView, AiSlotProvider } from './backend-settings.interface';
import type { PromptType } from '../utils/ai-prompt-settings.util';

export type AiModelSlot = 'fast' | 'intelligent';

export type AiConnectionStatus = 'idle' | 'checking' | 'success' | 'error';

export interface AiSectionProps {
  aiEnabled: boolean;
  setAiEnabled: (value: boolean) => void;
  aiWebSearchEnabled: boolean;
  setAiWebSearchEnabled: (value: boolean) => void;
  aiRateLimitEnabled: boolean;
  setAiRateLimitEnabled: (value: boolean) => void;
  aiCompletionTimeoutMs: number;
  setAiCompletionTimeoutMs: (value: number) => void;
  aiFastProvider: AiSlotProvider;
  setAiFastProvider: (value: AiSlotProvider) => void;
  aiFastEndpoint: string;
  setAiFastEndpoint: (value: string) => void;
  aiFastApiKey: string;
  setAiFastApiKey: (value: string) => void;
  aiFastModel: string;
  setAiFastModel: (value: string) => void;
  aiIntelligentProvider: AiSlotProvider;
  setAiIntelligentProvider: (value: AiSlotProvider) => void;
  aiIntelligentEndpoint: string;
  setAiIntelligentEndpoint: (value: string) => void;
  aiIntelligentApiKey: string;
  setAiIntelligentApiKey: (value: string) => void;
  aiIntelligentModel: string;
  setAiIntelligentModel: (value: string) => void;
  aiPrompt: string;
  setAiPrompt: (value: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (value: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (value: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (value: string) => void;
  aiImportPrompt: string;
  setAiImportPrompt: (value: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  showFastAiKey: boolean;
  setShowFastAiKey: (value: boolean) => void;
  showIntelligentAiKey: boolean;
  setShowIntelligentAiKey: (value: boolean) => void;
  openrouterModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  isLoadingModels: boolean;
  companies: string[];
  selectedFastCompany: string;
  setSelectedFastCompany: (value: string) => void;
  selectedIntelligentCompany: string;
  setSelectedIntelligentCompany: (value: string) => void;
  filteredFastModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  filteredIntelligentModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  localFastModels: string[];
  localIntelligentModels: string[];
  localFastModelMode: LocalAiModelMode;
  localIntelligentModelMode: LocalAiModelMode;
  onLocalModelSelection: (slot: AiModelSlot, value: string) => void;
  fastConnectionStatus: AiConnectionStatus;
  fastConnectionMessage: string;
  intelligentConnectionStatus: AiConnectionStatus;
  intelligentConnectionMessage: string;
  onTestAiConnection: (slot: AiModelSlot) => void;
}
