import React from 'react';
import { LocalAiModelMode } from './local-ai-model.interface';
import type { AiDefaultPromptsView, AiSlotProvider } from './backend-settings.interface';
import type { PromptType } from '../utils/ai-prompt-settings.util';
import type { AiConnectionStatus, AiModelSlot } from './ai-section-props.interface';

export interface ServerSettingsTabTemplateProps {
  dbType: 'local' | 'remote';
  setDbType: (type: 'local' | 'remote') => void;
  dbUrl: string;
  setDbUrl: (url: string) => void;
  publicAppUrl: string;
  setPublicAppUrl: (url: string) => void;
  oauthEnabled: boolean;
  setOauthEnabled: (enabled: boolean) => void;
  oauthIssuerUrl: string;
  setOauthIssuerUrl: (url: string) => void;
  oauthClientId: string;
  setOauthClientId: (id: string) => void;
  oauthClientSecret: string;
  setOauthClientSecret: (secret: string) => void;
  oauthButtonText: string;
  setOauthButtonText: (text: string) => void;
  oauthAutoRegister: boolean;
  setOauthAutoRegister: (enabled: boolean) => void;
  smtpType: 'local' | 'remote';
  setSmtpType: (type: 'local' | 'remote') => void;
  smtpHost: string;
  setSmtpHost: (host: string) => void;
  smtpPort: string;
  setSmtpPort: (port: string) => void;
  smtpUser: string;
  setSmtpUser: (user: string) => void;
  smtpPass: string;
  setSmtpPass: (pass: string) => void;
  smtpSecure: boolean;
  setSmtpSecure: (secure: boolean) => void;
  smtpFrom: string;
  setSmtpFrom: (from: string) => void;
  aiEnabled: boolean;
  setAiEnabled: (val: boolean) => void;
  aiWebSearchEnabled: boolean;
  setAiWebSearchEnabled: (val: boolean) => void;
  aiRateLimitEnabled: boolean;
  setAiRateLimitEnabled: (val: boolean) => void;
  aiCompletionTimeoutMs: number;
  setAiCompletionTimeoutMs: (val: number) => void;
  scrapeFetchTimeoutMs: number;
  setScrapeFetchTimeoutMs: (val: number) => void;
  scrapePlaywrightTimeoutMs: number;
  setScrapePlaywrightTimeoutMs: (val: number) => void;
  aiFastProvider: AiSlotProvider;
  setAiFastProvider: (val: AiSlotProvider) => void;
  aiFastEndpoint: string;
  setAiFastEndpoint: (val: string) => void;
  aiFastApiKey: string;
  setAiFastApiKey: (val: string) => void;
  aiFastModel: string;
  setAiFastModel: (val: string) => void;
  aiIntelligentProvider: AiSlotProvider;
  setAiIntelligentProvider: (val: AiSlotProvider) => void;
  aiIntelligentEndpoint: string;
  setAiIntelligentEndpoint: (val: string) => void;
  aiIntelligentApiKey: string;
  setAiIntelligentApiKey: (val: string) => void;
  aiIntelligentModel: string;
  setAiIntelligentModel: (val: string) => void;
  aiPrompt: string;
  setAiPrompt: (val: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (val: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (val: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (val: string) => void;
  aiImportPrompt: string;
  setAiImportPrompt: (val: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  showPassword: boolean;
  setShowPassword: (show: boolean) => void;
  showFastAiKey: boolean;
  setShowFastAiKey: (val: boolean) => void;
  showIntelligentAiKey: boolean;
  setShowIntelligentAiKey: (val: boolean) => void;
  openrouterModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  isLoadingModels: boolean;
  companies: string[];
  selectedFastCompany: string;
  setSelectedFastCompany: (val: string) => void;
  selectedIntelligentCompany: string;
  setSelectedIntelligentCompany: (val: string) => void;
  filteredFastModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  filteredIntelligentModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  localFastModels: string[];
  localIntelligentModels: string[];
  localFastModelMode: LocalAiModelMode;
  localIntelligentModelMode: LocalAiModelMode;
  onLocalModelSelection: (slot: AiModelSlot, value: string) => void;
  fastConnectionStatus: AiConnectionStatus;
  fastConnectionMessage: string;
  intelligentConnectionStatus: AiConnectionStatus;
  intelligentConnectionMessage: string;
  onTestAiConnection: (slot: AiModelSlot) => void;
  isLoading: boolean;
  isSaving: boolean;
  handleSave: (e: React.SubmitEvent<HTMLFormElement>) => void;
  isServerOwner: boolean;
  onDeleteServer: () => void;
  isDeletingServer: boolean;
}
