import React from 'react';
import { LocalAiModelMode } from './local-ai-model.interface';
import type { AiDefaultPromptsView } from './backend-settings.interface';
import type { PromptType } from '../utils/ai-prompt-settings.util';

export interface ServerSettingsTabTemplateProps {
  dbType: 'local' | 'remote';
  setDbType: (type: 'local' | 'remote') => void;
  dbUrl: string;
  setDbUrl: (url: string) => void;
  smtpType: 'local' | 'remote';
  setSmtpType: (type: 'local' | 'remote') => void;
  smtpHost: string;
  setSmtpHost: (host: string) => void;
  smtpPort: string;
  setSmtpPort: (port: string) => void;
  smtpUser: string;
  setSmtpUser: (user: string) => void;
  smtpPass: string;
  setSmtpPass: (pass: string) => void;
  smtpSecure: boolean;
  setSmtpSecure: (secure: boolean) => void;
  smtpFrom: string;
  setSmtpFrom: (from: string) => void;
  aiEnabled: boolean;
  setAiEnabled: (val: boolean) => void;
  aiProvider: 'gemini' | 'openai' | 'anthropic' | 'local' | 'openrouter';
  setAiProvider: (val: 'gemini' | 'openai' | 'anthropic' | 'local' | 'openrouter') => void;
  aiApiKey: string;
  setAiApiKey: (val: string) => void;
  aiModel: string;
  setAiModel: (val: string) => void;
  aiPrompt: string;
  setAiPrompt: (val: string) => void;
  aiDescriptionPrompt: string;
  setAiDescriptionPrompt: (val: string) => void;
  aiPopulatePrompt: string;
  setAiPopulatePrompt: (val: string) => void;
  aiCategoryPrompt: string;
  setAiCategoryPrompt: (val: string) => void;
  aiDefaultPrompts?: AiDefaultPromptsView;
  onResetPrompt: (type: PromptType) => void;
  aiEndpoint: string;
  setAiEndpoint: (val: string) => void;
  showPassword: boolean;
  setShowPassword: (show: boolean) => void;
  showAiKey: boolean;
  setShowAiKey: (val: boolean) => void;
  openrouterModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  isLoadingModels: boolean;
  companies: string[];
  selectedCompany: string;
  setSelectedCompany: (val: string) => void;
  filteredModels: Array<{ id: string; name: string; company: string; displayName: string }>;
  localAiModels: string[];
  localModelMode: LocalAiModelMode;
  onLocalModelSelection: (value: string) => void;
  aiConnectionStatus: 'idle' | 'checking' | 'success' | 'error';
  aiConnectionMessage: string;
  onTestAiConnection: () => void;
  isTestingAiConnection: boolean;
  isLoading: boolean;
  isSaving: boolean;
  handleSave: (e: React.SubmitEvent<HTMLFormElement>) => void;
  isServerOwner: boolean;
  onDeleteServer: () => void;
  isDeletingServer: boolean;
}
