import type { Item, ItemActions } from 'features/items';
import type { ItemViewMode } from 'features/items/interfaces/item-view-mode.type';
import type { ItemGroup } from '../../../interfaces/item-group.interface';

export interface Props {
  items: Item[];
  groupedItems: ItemGroup[];
  collapsedGroupKeys: Set<string>;
  toggleGroupCollapsed: (categoryKey: string) => void;
  viewMode: ItemViewMode;
  isLoading: boolean;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  canSuggest: boolean;
  canAutoAdd: boolean;
  openAutoAdd: () => void;
  openAddDrawer: () => void;
  enrichingItemIds: Set<string>;
  isOwner: boolean;
  isExpired: boolean;
  isArchived: boolean;
  canCollaborate: boolean;
  isPublicGuest?: boolean;
  isLocked: boolean;
  allowGroupFunds: boolean;
  aiEnabled: boolean;
  itemActions: ItemActions;
  isAddOpen: boolean;
  editingItem: Item | null;
  viewingItem: Item | null;
  isLinkingModeActive: boolean;
  isRelatingModeActive: boolean;
  isTaggingModeActive: boolean;
  isReplyTaggingModeActive: boolean;
  linkedItemIds: string[];
  relatedItemIds: string[];
  taggedItemIds: string[];
  replyTaggedItemIds: string[];
  isItemLinkCompatible: (item: Item) => boolean;
  isItemRelateCompatible: (item: Item) => boolean;
  handleLinkItemToggle: (itemId: string) => void;
  handleRelateItemToggle: (itemId: string) => void;
  handleSelectTag: (itemId: string) => void;
  handleSelectReplyTag: (itemId: string) => void;
  openItemEditor: (item: Item) => void;
  openItemViewer: (item: Item) => void;
  openClaimerSubstitutionCreate: (item: Item) => void;
  openClaimerSubstitutionEdit: (item: Item) => void;
  deleteClaimerSubstitution: (item: Item) => Promise<void>;
  openSubstitutionEdit: (item: Item, substitutionId: string) => void;
  deleteSubstitutionOption: (substitutionId: string) => Promise<void>;
  shouldOpenItemViewer: boolean;
  selectedItemId: string | null;
  setSelectedItemId: (id: string | null) => void;
  displayItems: Item[];
  handleItemTaggedClick: (itemId: string, returnToItemId?: string) => void;
  onLinkedItemsUnsupported: () => void;
  demoItemsTourTarget?: string;
}
