import React from 'react';
import { Priority } from 'features/wishlists';
import { FieldDefinition } from './item-field.interface';

export interface AddItemFormTemplateProps {
  name: string;
  setName: (val: string) => void;
  description: string;
  setDescription: (val: string) => void;
  priorityWeight: string;
  setPriorityWeight: (val: string) => void;
  priorityId?: string;
  setPriorityId?: (val: string) => void;
  isHiddenIdea: boolean;
  setIsHiddenIdea: (val: boolean) => void;
  priorities?: Priority[];
  isOwner: boolean;
  isLoading: boolean;
  errorMsg: string | null;
  handleSubmit: (e: React.SyntheticEvent) => void;
  showNewPriorityForm?: boolean;
  setShowNewPriorityForm?: (val: boolean) => void;
  newPriorityLabel?: string;
  setNewPriorityLabel?: (val: string) => void;
  newPriorityWeight?: string;
  setNewPriorityWeight?: (val: string) => void;
  newPriorityLoading?: boolean;
  handleCreatePriority?: (e: React.MouseEvent) => void;
  linkUrl: string;
  setLinkUrl: (val: string) => void;
  websiteName: string;
  setWebsiteName: (val: string) => void;
  category: string;
  setCategory: (val: string) => void;
  price: string;
  setPrice: (val: string) => void;
  isFavorite: boolean;
  setIsFavorite: (val: boolean) => void;
  isAutopopulating: boolean;
  hasScraped: boolean;
  handleScrapeClick: (e: React.MouseEvent) => void;
  pantsSize: string;
  setPantsSize: (val: string) => void;
  shirtSize: string;
  setShirtSize: (val: string) => void;
  shoesSize: string;
  setShoesSize: (val: string) => void;
  socksSize: string;
  setSocksSize: (val: string) => void;
  color: string;
  setColor: (val: string) => void;
  customFields: { id: string; name: string; value: string }[];
  handleAddCustomField: () => void;
  handleRemoveCustomField: (id: string) => void;
  handleUpdateCustomField: (id: string, key: 'name' | 'value', value: string) => void;
  showExtraFields: boolean;
  setShowExtraFields: (val: boolean) => void;
  renderedCategories: { id: string; label: string; isCustom?: boolean }[];
  isAddingCustom: boolean;
  setIsAddingCustom: (val: boolean) => void;
  newCustomInput: string;
  setNewCustomInput: (val: string) => void;
  handleAddCustomCategory: () => void;
  handleDeleteCustomCategory: (catId: string) => void;
  isScrapeButtonPulsing: boolean;
  isEdit?: boolean;
  definitions: FieldDefinition[];
  dynamicValues: Record<string, string>;
  isFieldVisible: (def: FieldDefinition) => boolean;
  handleUpdateDynamicValue: (key: string, val: string) => void;
  handleDeletePriority?: (id: string) => void;
  currentUserId?: string;
  otherUsersCanSee: boolean;
  setOtherUsersCanSee: (val: boolean) => void;
  claimOnCreate: boolean;
  setClaimOnCreate: (val: boolean) => void;
  isMultiCount: boolean;
  desiredQuantity: number | '';
  setDesiredQuantity: (val: number | '') => void;
  variations: { name: string; quantity: number }[];
  setVariations: React.Dispatch<React.SetStateAction<{ name: string; quantity: number }[]>>;
  linkedItemIds: string[];
  setLinkedItemIds: React.Dispatch<React.SetStateAction<string[]>>;
  wishlistItems?: any[];
  itemId?: string;
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
}
