import React from 'react';
import { Priority } from 'features/wishlists';
import { FieldDefinition } from './field-definition.interface';
import { ListShare } from 'features/wishlists/interfaces/list-share.interface';
import type { CustomFieldRow } from '../utils/add-item-custom-fields.util';
import type { ItemPhotoGalleryEntry } from '../components/photo-gallery/interfaces/item-photo-gallery-props.interface';

export interface AddItemFormTemplateProps {
  name: string;
  setName: (val: string) => void;
  description: string;
  setDescription: (val: string) => void;
  priorityWeight: string;
  setPriorityWeight: (val: string) => void;
  priorityId?: string;
  setPriorityId?: (val: string) => void;
  isHiddenIdea: boolean;
  setIsHiddenIdea: (val: boolean) => void;
  priorities?: Priority[];
  isOwner: boolean;
  isLoading: boolean;
  errorMsg: string | null;
  warningMsg: string | null;
  handleSubmit: (e: React.SyntheticEvent) => void;
  showNewPriorityForm?: boolean;
  setShowNewPriorityForm?: (val: boolean) => void;
  newPriorityLabel?: string;
  setNewPriorityLabel?: (val: string) => void;
  newPriorityWeight?: string;
  setNewPriorityWeight?: (val: string) => void;
  newPriorityLoading?: boolean;
  handleCreatePriority?: (e: React.MouseEvent) => void;
  linkUrl: string;
  setLinkUrl: (val: string) => void;
  websiteName: string;
  setWebsiteName: (val: string) => void;
  category: string;
  setCategory: (val: string) => void;
  price: string;
  setPrice: (val: string) => void;
  isFavorite: boolean;
  setIsFavorite: (val: boolean) => void;
  isAutopopulating: boolean;
  hasScraped: boolean;
  handleScrapeClick: (e: React.MouseEvent) => void;
  canUseWebSearchOnList?: boolean;
  customFields: CustomFieldRow[];
  handleAddCustomField: () => void;
  handleRemoveCustomField: (id: string) => void;
  handleUpdateCustomField: (id: string, key: 'name' | 'value', value: string) => void;
  editingCustomFieldNameId: string | null;
  onStartEditCustomFieldName: (id: string) => void;
  onFinishEditCustomFieldName: () => void;
  hasIncompleteCustomFields: boolean;
  showExtraFields: boolean;
  setShowExtraFields: (val: boolean) => void;
  renderedCategories: { id: string; label: string; isCustom?: boolean; isFromList?: boolean }[];
  aiCategoryChips: Array<{ id: string; label: string; variant: 'primary' | 'suggestion' }>;
  aiCategoryIds: Set<string>;
  isAddingCustom: boolean;
  setIsAddingCustom: (val: boolean) => void;
  newCustomInput: string;
  setNewCustomInput: (val: string) => void;
  handleAddCustomCategory: () => void;
  handleDeleteCustomCategory: (catId: string) => void;
  isScrapeButtonPulsing: boolean;
  isEdit?: boolean;
  definitions: FieldDefinition[];
  dynamicValues: Record<string, string>;
  isFieldVisible: (def: FieldDefinition) => boolean;
  handleUpdateDynamicValue: (key: string, val: string) => void;
  handleDeletePriority?: (id: string) => void;
  currentUserId?: string;
  otherUsersCanSee: boolean;
  setOtherUsersCanSee: (val: boolean) => void;
  claimOnCreate: boolean;
  setClaimOnCreate: (val: boolean) => void;
  isMultiCount: boolean;
  isSuggestion: boolean;
  desiredQuantity: number | '';
  setDesiredQuantity: (val: number | '') => void;
  variations: { name: string; quantity: number }[];
  setVariations: React.Dispatch<React.SetStateAction<{ name: string; quantity: number }[]>>;
  linkedItemIds: string[];
  resolvedLinkedCount: number;
  relatedItemIds: string[];
  resolvedRelatedCount: number;
  wishlistItems?: any[];
  itemId?: string;
  isLinkingModeActive: boolean;
  setIsLinkingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  isRelatingModeActive: boolean;
  setIsRelatingModeActive: React.Dispatch<React.SetStateAction<boolean>>;
  getFriendlyCategoryLabel: (id: string) => string;
  showFieldDefinitions: boolean;
  varName: string;
  setVarName: (val: string) => void;
  varQty: number | '';
  setVarQty: (val: number | '') => void;
  varError: string | null;
  handleAddVariation: () => void;
  handleVarQtyChange: (val: string) => void;
  listShares: ListShare[];
  sharedWithUserIds: string[];
  setSharedWithUserIds: (userIds: string[]) => void;
  visibilityMode: 'everyone' | 'restricted' | 'private';
  onVisibilityModeChange: (mode: 'everyone' | 'restricted' | 'private') => void;
  canShowAi?: boolean;
  listAiEnabled?: boolean;
  canSummarizeNotes: boolean;
  isSummarizingNotes: boolean;
  canUndoSummarize: boolean;
  onSummarizeNotes: () => void;
  onUndoSummarize: () => void;
  showPhotoGallery: boolean;
  photoEntries: ItemPhotoGalleryEntry[];
  onPhotoEntriesChange: (photos: ItemPhotoGalleryEntry[]) => void;
  photoError: string | null;
  onPhotoError: (message: string | null) => void;
  readOnly?: boolean;
}
