import { ItemLink } from './item-link.interface';
import { Claim } from './item-claim.interface';
import { ItemAudienceUser } from './item-audience-user.interface';
import type { ItemDescriptionMetadata } from 'shared/interfaces/item-description-metadata.interface';
import type { ItemPhoto } from './item-photo.interface';
import type { ItemSubstitutionOption } from './item-substitution.interface';

export interface Item {
  Id: string;
  ListId: string;
  PriorityId: string | null;
  SuggestedByUserId: string | null;
  SuggestedByUsername?: string | null;
  SuggestedByFirstName?: string | null;
  SuggestedByLastName?: string | null;
  Name: string;
  Description: string | null;
  IsHiddenIdea: boolean;
  IsSuggestion?: boolean;
  Category: string;
  CategoryKey?: string;
  CategoryLabel?: string;
  Priority?: number | null;
  CreatedAt?: string;
  SharedWith?: ItemAudienceUser[];
  Links: ItemLink[];
  Claims: Claim[];
  IsClaimed: boolean;
  Photos?: ItemPhoto[];
  Metadata?: ItemDescriptionMetadata | null;
  IsFullyClaimed?: boolean;
  IsMultiCount?: boolean;
  TotalClaimedAmount?: number;
  TotalClaimedQuantity?: number;
  DesiredQuantity?: number | null;
  RemainingQuantity?: number | null;
  FundingTarget?: number;
  AllowSubstitutions?: boolean;
  SubstitutionOptions?: ItemSubstitutionOption[];
  ActiveSubstitutionId?: string | null;
}
